[2025-05-02T15:13:10.799+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data.get_original_data scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T15:13:10.805+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data.get_original_data scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T15:13:10.806+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-02T15:13:10.815+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): get_original_data> on 2025-05-01 00:00:00+00:00
[2025-05-02T15:13:10.819+0000] {standard_task_runner.py:60} INFO - Started process 511 to run task
[2025-05-02T15:13:10.821+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data', 'get_original_data', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmpwg10zq73']
[2025-05-02T15:13:10.823+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask get_original_data
[2025-05-02T15:13:10.864+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data.get_original_data scheduled__2025-05-01T00:00:00+00:00 [running]> on host 612cef286438
[2025-05-02T15:13:10.921+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data' AIRFLOW_CTX_TASK_ID='get_original_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-02T15:13:10.923+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvuz8h8esv --system-site-packages --python=python
[2025-05-02T15:13:10.930+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T15:13:11.662+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 403ms
[2025-05-02T15:13:11.663+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvuz8h8esv, clear=False, no_vcs_ignore=False, global=True)
[2025-05-02T15:13:11.664+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmpeepfwy2k)
[2025-05-02T15:13:11.664+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-02T15:13:11.664+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-02T15:13:11.688+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvuz8h8esv/bin/pip install -r /tmp/venvuz8h8esv/requirements.txt
[2025-05-02T15:13:11.694+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T15:13:12.337+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-02T15:13:12.592+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venvuz8h8esv/requirements.txt (line 1))
[2025-05-02T15:13:12.780+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-02T15:13:12.782+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvuz8h8esv/requirements.txt (line 2)) (2.0.3)
[2025-05-02T15:13:12.818+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvuz8h8esv/requirements.txt (line 1)) (1.37.38)
[2025-05-02T15:13:12.819+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvuz8h8esv/requirements.txt (line 1)) (1.37.38)
[2025-05-02T15:13:12.820+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvuz8h8esv/requirements.txt (line 1)) (1.24.4)
[2025-05-02T15:13:12.821+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvuz8h8esv/requirements.txt (line 1)) (23.2)
[2025-05-02T15:13:12.822+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvuz8h8esv/requirements.txt (line 1)) (14.0.2)
[2025-05-02T15:13:12.822+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvuz8h8esv/requirements.txt (line 1)) (4.9.0)
[2025-05-02T15:13:12.885+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvuz8h8esv/requirements.txt (line 2)) (2.8.2)
[2025-05-02T15:13:12.886+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvuz8h8esv/requirements.txt (line 2)) (2023.3.post1)
[2025-05-02T15:13:12.887+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvuz8h8esv/requirements.txt (line 2)) (2023.4)
[2025-05-02T15:13:12.891+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvuz8h8esv/requirements.txt (line 1)) (0.10.0)
[2025-05-02T15:13:12.891+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvuz8h8esv/requirements.txt (line 1)) (0.11.5)
[2025-05-02T15:13:12.898+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvuz8h8esv/requirements.txt (line 1)) (1.26.18)
[2025-05-02T15:13:12.902+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas->-r /tmp/venvuz8h8esv/requirements.txt (line 2)) (1.16.0)
[2025-05-02T15:13:12.937+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-02T15:13:12.964+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 16.0 MB/s eta 0:00:00
[2025-05-02T15:13:15.028+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-02T15:13:15.245+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-02T15:13:15.326+0000] {process_utils.py:190} INFO - 
[2025-05-02T15:13:15.330+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-02T15:13:15.331+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-02T15:13:15.508+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvuz8h8esv/bin/python /tmp/venv-call_9n6a8_p/script.py /tmp/venv-call_9n6a8_p/script.in /tmp/venv-call_9n6a8_p/script.out /tmp/venv-call_9n6a8_p/string_args.txt /tmp/venv-call_9n6a8_p/termination.log
[2025-05-02T15:13:15.514+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T15:13:16.170+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-02T15:13:18.468+0000] {process_utils.py:190} INFO - [[34m2025-05-02T15:13:18.467+0000[0m] {[34mscript.py:[0m47} INFO[0m - Starting to read the dataset from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-02T15:13:18.492+0000] {process_utils.py:190} INFO - [[34m2025-05-02T15:13:18.491+0000[0m] {[34mscript.py:[0m57} INFO[0m - Dataset read successfully from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-02T15:13:18.493+0000] {process_utils.py:190} INFO - [[34m2025-05-02T15:13:18.492+0000[0m] {[34mscript.py:[0m58} INFO[0m - Dataset shape: (5110, 12)[0m
[2025-05-02T15:13:18.494+0000] {process_utils.py:190} INFO - [[34m2025-05-02T15:13:18.494+0000[0m] {[34mscript.py:[0m75} INFO[0m - Dataset columns: ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke'][0m
[2025-05-02T15:13:18.495+0000] {process_utils.py:190} INFO - [[34m2025-05-02T15:13:18.494+0000[0m] {[34mscript.py:[0m81} INFO[0m - Starting to save the dataset to S3/Minio at s3://data/raw/stroke_data.csv[0m
[2025-05-02T15:13:18.504+0000] {process_utils.py:190} INFO - [[34m2025-05-02T15:13:18.503+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T15:13:18.608+0000] {process_utils.py:190} INFO - [[34m2025-05-02T15:13:18.607+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T15:13:18.652+0000] {process_utils.py:190} INFO - [[34m2025-05-02T15:13:18.651+0000[0m] {[34mscript.py:[0m86} INFO[0m - Dataset saved successfully to s3://data/raw/stroke_data.csv[0m
[2025-05-02T15:13:18.939+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-02T15:13:18.951+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data, task_id=get_original_data, execution_date=20250501T000000, start_date=20250502T151310, end_date=20250502T151318
[2025-05-02T15:13:18.985+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-02T15:13:19.010+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-02T15:59:45.820+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data.get_original_data scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T15:59:45.827+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data.get_original_data scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T15:59:45.827+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-02T15:59:45.837+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): get_original_data> on 2025-05-01 00:00:00+00:00
[2025-05-02T15:59:45.841+0000] {standard_task_runner.py:60} INFO - Started process 542 to run task
[2025-05-02T15:59:45.844+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data', 'get_original_data', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmp1237ck37']
[2025-05-02T15:59:45.845+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask get_original_data
[2025-05-02T15:59:45.880+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data.get_original_data scheduled__2025-05-01T00:00:00+00:00 [running]> on host 936bf26779ff
[2025-05-02T15:59:45.931+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data' AIRFLOW_CTX_TASK_ID='get_original_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-02T15:59:45.933+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvnrdxo5el --system-site-packages --python=python
[2025-05-02T15:59:45.939+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T15:59:46.685+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 417ms
[2025-05-02T15:59:46.685+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvnrdxo5el, clear=False, no_vcs_ignore=False, global=True)
[2025-05-02T15:59:46.686+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmpto22ndyy)
[2025-05-02T15:59:46.686+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-02T15:59:46.687+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-02T15:59:46.715+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvnrdxo5el/bin/pip install -r /tmp/venvnrdxo5el/requirements.txt
[2025-05-02T15:59:46.721+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T15:59:47.397+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-02T15:59:47.791+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venvnrdxo5el/requirements.txt (line 1))
[2025-05-02T15:59:47.873+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-02T15:59:47.877+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvnrdxo5el/requirements.txt (line 2)) (2.0.3)
[2025-05-02T15:59:47.909+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvnrdxo5el/requirements.txt (line 1)) (1.37.38)
[2025-05-02T15:59:47.910+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvnrdxo5el/requirements.txt (line 1)) (1.37.38)
[2025-05-02T15:59:47.911+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvnrdxo5el/requirements.txt (line 1)) (1.24.4)
[2025-05-02T15:59:47.911+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvnrdxo5el/requirements.txt (line 1)) (23.2)
[2025-05-02T15:59:47.911+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvnrdxo5el/requirements.txt (line 1)) (14.0.2)
[2025-05-02T15:59:47.912+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvnrdxo5el/requirements.txt (line 1)) (4.9.0)
[2025-05-02T15:59:47.972+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvnrdxo5el/requirements.txt (line 2)) (2.8.2)
[2025-05-02T15:59:47.973+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvnrdxo5el/requirements.txt (line 2)) (2023.3.post1)
[2025-05-02T15:59:47.974+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvnrdxo5el/requirements.txt (line 2)) (2023.4)
[2025-05-02T15:59:47.976+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvnrdxo5el/requirements.txt (line 1)) (0.10.0)
[2025-05-02T15:59:47.977+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvnrdxo5el/requirements.txt (line 1)) (0.11.5)
[2025-05-02T15:59:47.982+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvnrdxo5el/requirements.txt (line 1)) (1.26.18)
[2025-05-02T15:59:47.988+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas->-r /tmp/venvnrdxo5el/requirements.txt (line 2)) (1.16.0)
[2025-05-02T15:59:48.020+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-02T15:59:48.045+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 17.0 MB/s eta 0:00:00
[2025-05-02T15:59:50.148+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-02T15:59:50.332+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-02T15:59:50.430+0000] {process_utils.py:190} INFO - 
[2025-05-02T15:59:50.432+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-02T15:59:50.432+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-02T15:59:50.563+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvnrdxo5el/bin/python /tmp/venv-callgqrkl84y/script.py /tmp/venv-callgqrkl84y/script.in /tmp/venv-callgqrkl84y/script.out /tmp/venv-callgqrkl84y/string_args.txt /tmp/venv-callgqrkl84y/termination.log
[2025-05-02T15:59:50.571+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T15:59:51.093+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-02T15:59:52.758+0000] {process_utils.py:190} INFO - [[34m2025-05-02T15:59:52.757+0000[0m] {[34mscript.py:[0m47} INFO[0m - Starting to read the dataset from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-02T15:59:52.778+0000] {process_utils.py:190} INFO - [[34m2025-05-02T15:59:52.777+0000[0m] {[34mscript.py:[0m57} INFO[0m - Dataset read successfully from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-02T15:59:52.778+0000] {process_utils.py:190} INFO - [[34m2025-05-02T15:59:52.778+0000[0m] {[34mscript.py:[0m58} INFO[0m - Dataset shape: (5110, 12)[0m
[2025-05-02T15:59:52.780+0000] {process_utils.py:190} INFO - [[34m2025-05-02T15:59:52.779+0000[0m] {[34mscript.py:[0m74} INFO[0m - Dataset columns: ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke'][0m
[2025-05-02T15:59:52.780+0000] {process_utils.py:190} INFO - [[34m2025-05-02T15:59:52.779+0000[0m] {[34mscript.py:[0m80} INFO[0m - Starting to save the dataset to S3/Minio at s3://data/raw/stroke_data.csv[0m
[2025-05-02T15:59:52.789+0000] {process_utils.py:190} INFO - [[34m2025-05-02T15:59:52.789+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T15:59:52.861+0000] {process_utils.py:190} INFO - [[34m2025-05-02T15:59:52.861+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T15:59:52.899+0000] {process_utils.py:190} INFO - [[34m2025-05-02T15:59:52.899+0000[0m] {[34mscript.py:[0m85} INFO[0m - Dataset saved successfully to s3://data/raw/stroke_data.csv[0m
[2025-05-02T15:59:53.110+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-02T15:59:53.119+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data, task_id=get_original_data, execution_date=20250501T000000, start_date=20250502T155945, end_date=20250502T155953
[2025-05-02T15:59:53.168+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-02T15:59:53.198+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
