[2025-05-03T00:53:21.690+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.feature_engineering scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T00:53:21.698+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.feature_engineering scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T00:53:21.698+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-03T00:53:21.709+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): feature_engineering> on 2025-05-02 00:00:00+00:00
[2025-05-03T00:53:21.713+0000] {standard_task_runner.py:60} INFO - Started process 419 to run task
[2025-05-03T00:53:21.715+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'feature_engineering', 'scheduled__2025-05-02T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmpuvgrf4rg']
[2025-05-03T00:53:21.716+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask feature_engineering
[2025-05-03T00:53:21.753+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.feature_engineering scheduled__2025-05-02T00:00:00+00:00 [running]> on host c624b4368fe1
[2025-05-03T00:53:21.805+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='feature_engineering' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-02T00:00:00+00:00'
[2025-05-03T00:53:21.807+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv4g8r7ro8 --system-site-packages --python=python
[2025-05-03T00:53:21.812+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T00:53:22.369+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 288ms
[2025-05-03T00:53:22.370+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv4g8r7ro8, clear=False, no_vcs_ignore=False, global=True)
[2025-05-03T00:53:22.370+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmplpcp5ohi)
[2025-05-03T00:53:22.371+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-03T00:53:22.371+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-03T00:53:22.393+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv4g8r7ro8/bin/pip install -r /tmp/venv4g8r7ro8/requirements.txt
[2025-05-03T00:53:22.400+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T00:53:23.000+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-03T00:53:23.219+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venv4g8r7ro8/requirements.txt (line 1))
[2025-05-03T00:53:23.255+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-03T00:53:23.257+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv4g8r7ro8/requirements.txt (line 2)) (1.37.38)
[2025-05-03T00:53:23.258+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (2.17.2)
[2025-05-03T00:53:23.308+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv4g8r7ro8/requirements.txt (line 1)) (1.37.38)
[2025-05-03T00:53:23.309+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv4g8r7ro8/requirements.txt (line 1)) (1.24.4)
[2025-05-03T00:53:23.310+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv4g8r7ro8/requirements.txt (line 1)) (23.2)
[2025-05-03T00:53:23.311+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv4g8r7ro8/requirements.txt (line 1)) (2.0.3)
[2025-05-03T00:53:23.311+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv4g8r7ro8/requirements.txt (line 1)) (14.0.2)
[2025-05-03T00:53:23.312+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv4g8r7ro8/requirements.txt (line 1)) (4.9.0)
[2025-05-03T00:53:23.321+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venv4g8r7ro8/requirements.txt (line 2)) (0.10.0)
[2025-05-03T00:53:23.322+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venv4g8r7ro8/requirements.txt (line 2)) (0.11.5)
[2025-05-03T00:53:23.375+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (2.17.2)
[2025-05-03T00:53:23.376+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (2.2.5)
[2025-05-03T00:53:23.377+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (1.13.1)
[2025-05-03T00:53:23.378+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (7.0.0)
[2025-05-03T00:53:23.378+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (3.4.3)
[2025-05-03T00:53:23.379+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (3.5.2)
[2025-05-03T00:53:23.379+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (3.7.5)
[2025-05-03T00:53:23.380+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (1.3.2)
[2025-05-03T00:53:23.381+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (1.10.1)
[2025-05-03T00:53:23.382+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (1.4.51)
[2025-05-03T00:53:23.383+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (3.1.3)
[2025-05-03T00:53:23.384+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (21.2.0)
[2025-05-03T00:53:23.426+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (5.3.2)
[2025-05-03T00:53:23.427+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (8.1.7)
[2025-05-03T00:53:23.427+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (3.1.1)
[2025-05-03T00:53:23.428+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (0.51.0)
[2025-05-03T00:53:23.429+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (3.1.44)
[2025-05-03T00:53:23.430+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (6.11.0)
[2025-05-03T00:53:23.431+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (1.22.0)
[2025-05-03T00:53:23.431+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (1.22.0)
[2025-05-03T00:53:23.432+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (4.25.2)
[2025-05-03T00:53:23.432+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (6.0.1)
[2025-05-03T00:53:23.433+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (2.31.0)
[2025-05-03T00:53:23.434+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (0.4.4)
[2025-05-03T00:53:23.442+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (1.3.0)
[2025-05-03T00:53:23.443+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (5.13.0)
[2025-05-03T00:53:23.450+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venv4g8r7ro8/requirements.txt (line 1)) (2.8.2)
[2025-05-03T00:53:23.451+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venv4g8r7ro8/requirements.txt (line 1)) (1.26.18)
[2025-05-03T00:53:23.464+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (2.2.3)
[2025-05-03T00:53:23.465+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (2.1.2)
[2025-05-03T00:53:23.485+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (3.2.6)
[2025-05-03T00:53:23.486+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (3.2.0)
[2025-05-03T00:53:23.496+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (2.1.3)
[2025-05-03T00:53:23.558+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (1.1.1)
[2025-05-03T00:53:23.559+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (0.12.1)
[2025-05-03T00:53:23.559+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (4.57.0)
[2025-05-03T00:53:23.560+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (1.4.7)
[2025-05-03T00:53:23.561+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (10.4.0)
[2025-05-03T00:53:23.561+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (3.1.1)
[2025-05-03T00:53:23.640+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venv4g8r7ro8/requirements.txt (line 1)) (2023.3.post1)
[2025-05-03T00:53:23.641+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venv4g8r7ro8/requirements.txt (line 1)) (2023.4)
[2025-05-03T00:53:23.688+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (1.4.2)
[2025-05-03T00:53:23.689+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (3.5.0)
[2025-05-03T00:53:23.772+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (3.0.3)
[2025-05-03T00:53:23.841+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (2.26.2)
[2025-05-03T00:53:23.897+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (4.0.12)
[2025-05-03T00:53:23.939+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (3.17.0)
[2025-05-03T00:53:23.978+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (1.2.14)
[2025-05-03T00:53:23.986+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (0.43b0)
[2025-05-03T00:53:24.027+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venv4g8r7ro8/requirements.txt (line 1)) (1.16.0)
[2025-05-03T00:53:24.052+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (3.3.2)
[2025-05-03T00:53:24.053+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (3.6)
[2025-05-03T00:53:24.054+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (2023.11.17)
[2025-05-03T00:53:24.136+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (1.16.0)
[2025-05-03T00:53:24.144+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (5.0.2)
[2025-05-03T00:53:24.166+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (0.3.0)
[2025-05-03T00:53:24.167+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (4.9)
[2025-05-03T00:53:24.207+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv4g8r7ro8/requirements.txt (line 3)) (0.5.1)
[2025-05-03T00:53:24.247+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-03T00:53:24.270+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 18.9 MB/s eta 0:00:00
[2025-05-03T00:53:26.611+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-03T00:53:26.817+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-03T00:53:26.950+0000] {process_utils.py:190} INFO - 
[2025-05-03T00:53:26.951+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-03T00:53:26.951+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-03T00:53:27.170+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv4g8r7ro8/bin/python /tmp/venv-callay6kt8kg/script.py /tmp/venv-callay6kt8kg/script.in /tmp/venv-callay6kt8kg/script.out /tmp/venv-callay6kt8kg/string_args.txt /tmp/venv-callay6kt8kg/termination.log
[2025-05-03T00:53:27.176+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T00:53:27.706+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-03T00:53:28.995+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:28.993+0000[0m] {[34mscript.py:[0m61} INFO[0m - Loading dataset from S3/Minio[0m
[2025-05-03T00:53:29.010+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.009+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T00:53:29.215+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.215+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T00:53:29.280+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.280+0000[0m] {[34mscript.py:[0m69} INFO[0m - Dataset loaded successfully from s3://data/raw/stroke_data.csv[0m
[2025-05-03T00:53:29.281+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.280+0000[0m] {[34mscript.py:[0m70} INFO[0m - Dataset shape: (5110, 12)[0m
[2025-05-03T00:53:29.282+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.280+0000[0m] {[34mscript.py:[0m71} INFO[0m - Dataset columns: ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke'][0m
[2025-05-03T00:53:29.282+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.281+0000[0m] {[34mscript.py:[0m77} INFO[0m - Limpiando datos eliminando duplicados y manejando valores nulos[0m
[2025-05-03T00:53:29.288+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.288+0000[0m] {[34mscript.py:[0m85} INFO[0m - Removed 0 duplicate rows[0m
[2025-05-03T00:53:29.290+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.289+0000[0m] {[34mscript.py:[0m91} INFO[0m - Imputed 0 null values in 'bmi' column with median value[0m
[2025-05-03T00:53:29.291+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.291+0000[0m] {[34mscript.py:[0m104} INFO[0m - No null values remaining in the dataset[0m
[2025-05-03T00:53:29.291+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.291+0000[0m] {[34mscript.py:[0m107} INFO[0m - Iniciando ingeniería de características[0m
[2025-05-03T00:53:29.292+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.291+0000[0m] {[34mscript.py:[0m55} INFO[0m - Applying One-Hot Encoding to columns: ['gender', 'ever_married', 'work_type', 'residence_type', 'smoking_status'][0m
[2025-05-03T00:53:29.298+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.298+0000[0m] {[34mscript.py:[0m114} INFO[0m - Applied one-hot encoding to categorical features[0m
[2025-05-03T00:53:29.299+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.298+0000[0m] {[34mscript.py:[0m121} INFO[0m - Removed 'id' column as it's not relevant for prediction[0m
[2025-05-03T00:53:29.301+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.301+0000[0m] {[34mscript.py:[0m133} INFO[0m - Truncated 0 extreme values in 'age' column at 82.0[0m
[2025-05-03T00:53:29.304+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.304+0000[0m] {[34mscript.py:[0m133} INFO[0m - Truncated 52 extreme values in 'avg_glucose_level' column at 240.7082[0m
[2025-05-03T00:53:29.305+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.305+0000[0m] {[34mscript.py:[0m133} INFO[0m - Truncated 5 extreme values in 'bmi' column at 66.6[0m
[2025-05-03T00:53:29.306+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.305+0000[0m] {[34mscript.py:[0m135} INFO[0m - Feature engineering completed[0m
[2025-05-03T00:53:29.306+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.305+0000[0m] {[34mscript.py:[0m138} INFO[0m - Saving processed dataset to s3://data/processed/stroke_data.csv[0m
[2025-05-03T00:53:29.314+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.314+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T00:53:29.406+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.406+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T00:53:29.444+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.444+0000[0m] {[34mscript.py:[0m142} INFO[0m - Processed dataset saved successfully to s3://data/processed/stroke_data.csv[0m
[2025-05-03T00:53:29.445+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.444+0000[0m] {[34mscript.py:[0m148} INFO[0m - Updating dataset information in S3/Minio[0m
[2025-05-03T00:53:29.451+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.451+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T00:53:29.561+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.561+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T00:53:29.572+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.571+0000[0m] {[34mscript.py:[0m163} INFO[0m - No existing dataset information found, initializing new info dictionary[0m
[2025-05-03T00:53:29.575+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.574+0000[0m] {[34mscript.py:[0m178} INFO[0m - Target column for dataset: log_cnt[0m
[2025-05-03T00:53:29.575+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.575+0000[0m] {[34mscript.py:[0m182} ERROR[0m - Target column 'log_cnt' not found in DataFrame. Available columns: ['age', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi', 'stroke', 'gender_Male', 'gender_Other', 'ever_married_Yes', 'work_type_Never_worked', 'work_type_Private', 'work_type_Self-employed', 'work_type_children', 'residence_type_Urban', 'smoking_status_formerly smoked', 'smoking_status_never smoked', 'smoking_status_smokes'][0m
[2025-05-03T00:53:29.578+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.578+0000[0m] {[34mvariable.py:[0m245} WARNING[0m - The variable target_col is defined in the LocalFilesystemBackend secrets backend, which takes precedence over reading from the database. The value in the database will be updated, but to read it you have to delete the conflicting variable from LocalFilesystemBackend[0m
[2025-05-03T00:53:29.924+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.923+0000[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2025-05-03T00:53:29.927+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.927+0000[0m] {[34mscript.py:[0m186} INFO[0m - Setting target column to default value: stroke[0m
[2025-05-03T00:53:29.935+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.935+0000[0m] {[34mscript.py:[0m216} INFO[0m - Dataset information updated successfully in S3/Minio[0m
[2025-05-03T00:53:29.935+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:29.935+0000[0m] {[34mscript.py:[0m222} INFO[0m - Logging data to MLflow[0m
[2025-05-03T00:53:30.136+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/data/dataset_source_registry.py:149 UserWarning: Failed to determine whether UCVolumeDatasetSource can resolve source information for 'local file: healthcare-dataset-stroke-data.csv'. Exception:
[2025-05-03T00:53:30.137+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/data/dataset_source_registry.py:149 UserWarning: The specified dataset source can be interpreted in multiple ways: LocalArtifactDatasetSource, LocalArtifactDatasetSource. MLflow will assume that this is a LocalArtifactDatasetSource source.
[2025-05-03T00:53:30.180+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/types/utils.py:407 UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
[2025-05-03T00:53:30.196+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:30.196+0000[0m] {[34mscript.py:[0m271} INFO[0m - Dataset logged to MLflow successfully in run: feature_engineering_20250503_005329[0m
[2025-05-03T00:53:30.216+0000] {process_utils.py:190} INFO - 2025/05/03 00:53:30 INFO mlflow.tracking._tracking_service.client: 🏃 View run feature_engineering_20250503_005329 at: http://mlflow:5000/#/experiments/1/runs/ec77dd968ecc4fe691553f05a98f137f.
[2025-05-03T00:53:30.217+0000] {process_utils.py:190} INFO - 2025/05/03 00:53:30 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-03T00:53:30.236+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:30.235+0000[0m] {[34mscript.py:[0m273} INFO[0m - MLflow run ended[0m
[2025-05-03T00:53:30.645+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-03T00:53:30.655+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=feature_engineering, execution_date=20250502T000000, start_date=20250503T005321, end_date=20250503T005330
[2025-05-03T00:53:30.690+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-03T00:53:30.709+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-03T04:58:18.876+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.feature_engineering scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T04:58:18.882+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.feature_engineering scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T04:58:18.883+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-03T04:58:18.894+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): feature_engineering> on 2025-05-02 00:00:00+00:00
[2025-05-03T04:58:18.899+0000] {standard_task_runner.py:60} INFO - Started process 798 to run task
[2025-05-03T04:58:18.901+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'feature_engineering', 'scheduled__2025-05-02T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmpbpf4zulw']
[2025-05-03T04:58:18.903+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask feature_engineering
[2025-05-03T04:58:18.946+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.feature_engineering scheduled__2025-05-02T00:00:00+00:00 [running]> on host 75c2609a33dd
[2025-05-03T04:58:19.002+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='feature_engineering' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-02T00:00:00+00:00'
[2025-05-03T04:58:19.005+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv5k1nx6tc --system-site-packages --python=python
[2025-05-03T04:58:19.012+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T04:58:19.806+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 491ms
[2025-05-03T04:58:19.807+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv5k1nx6tc, clear=False, no_vcs_ignore=False, global=True)
[2025-05-03T04:58:19.808+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmpfgk88_et)
[2025-05-03T04:58:19.808+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-03T04:58:19.809+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-03T04:58:19.841+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv5k1nx6tc/bin/pip install -r /tmp/venv5k1nx6tc/requirements.txt
[2025-05-03T04:58:19.853+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T04:58:20.665+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-03T04:58:20.902+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venv5k1nx6tc/requirements.txt (line 1))
[2025-05-03T04:58:20.951+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-03T04:58:20.953+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv5k1nx6tc/requirements.txt (line 2)) (1.37.38)
[2025-05-03T04:58:20.954+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (2.17.2)
[2025-05-03T04:58:20.991+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv5k1nx6tc/requirements.txt (line 1)) (1.37.38)
[2025-05-03T04:58:20.992+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv5k1nx6tc/requirements.txt (line 1)) (1.24.4)
[2025-05-03T04:58:20.992+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv5k1nx6tc/requirements.txt (line 1)) (23.2)
[2025-05-03T04:58:20.994+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv5k1nx6tc/requirements.txt (line 1)) (2.0.3)
[2025-05-03T04:58:20.994+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv5k1nx6tc/requirements.txt (line 1)) (14.0.2)
[2025-05-03T04:58:20.995+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv5k1nx6tc/requirements.txt (line 1)) (4.9.0)
[2025-05-03T04:58:21.003+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venv5k1nx6tc/requirements.txt (line 2)) (0.10.0)
[2025-05-03T04:58:21.004+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venv5k1nx6tc/requirements.txt (line 2)) (0.11.5)
[2025-05-03T04:58:21.049+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (2.17.2)
[2025-05-03T04:58:21.094+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (2.2.5)
[2025-05-03T04:58:21.111+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (1.13.1)
[2025-05-03T04:58:21.127+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (7.0.0)
[2025-05-03T04:58:21.135+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (3.4.3)
[2025-05-03T04:58:21.137+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (3.5.2)
[2025-05-03T04:58:21.138+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (3.7.5)
[2025-05-03T04:58:21.140+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (1.3.2)
[2025-05-03T04:58:21.141+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (1.10.1)
[2025-05-03T04:58:21.144+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (1.4.51)
[2025-05-03T04:58:21.144+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (3.1.3)
[2025-05-03T04:58:21.145+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (21.2.0)
[2025-05-03T04:58:21.147+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (5.3.2)
[2025-05-03T04:58:21.148+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (8.1.7)
[2025-05-03T04:58:21.149+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (3.1.1)
[2025-05-03T04:58:21.151+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (0.51.0)
[2025-05-03T04:58:21.152+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (3.1.44)
[2025-05-03T04:58:21.153+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (6.11.0)
[2025-05-03T04:58:21.153+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (1.22.0)
[2025-05-03T04:58:21.153+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (1.22.0)
[2025-05-03T04:58:21.154+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (4.25.2)
[2025-05-03T04:58:21.154+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (6.0.1)
[2025-05-03T04:58:21.155+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (2.31.0)
[2025-05-03T04:58:21.155+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (0.4.4)
[2025-05-03T04:58:21.156+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (1.3.0)
[2025-05-03T04:58:21.156+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (5.13.0)
[2025-05-03T04:58:21.157+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venv5k1nx6tc/requirements.txt (line 1)) (2.8.2)
[2025-05-03T04:58:21.157+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venv5k1nx6tc/requirements.txt (line 1)) (1.26.18)
[2025-05-03T04:58:21.157+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (2.2.3)
[2025-05-03T04:58:21.158+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (2.1.2)
[2025-05-03T04:58:21.165+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (3.2.6)
[2025-05-03T04:58:21.166+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (3.2.0)
[2025-05-03T04:58:21.176+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (2.1.3)
[2025-05-03T04:58:21.206+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (1.1.1)
[2025-05-03T04:58:21.207+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (0.12.1)
[2025-05-03T04:58:21.208+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (4.57.0)
[2025-05-03T04:58:21.208+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (1.4.7)
[2025-05-03T04:58:21.210+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (10.4.0)
[2025-05-03T04:58:21.210+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (3.1.1)
[2025-05-03T04:58:21.288+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venv5k1nx6tc/requirements.txt (line 1)) (2023.3.post1)
[2025-05-03T04:58:21.289+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venv5k1nx6tc/requirements.txt (line 1)) (2023.4)
[2025-05-03T04:58:21.321+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (1.4.2)
[2025-05-03T04:58:21.321+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (3.5.0)
[2025-05-03T04:58:21.411+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (3.0.3)
[2025-05-03T04:58:21.473+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (2.26.2)
[2025-05-03T04:58:21.526+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (4.0.12)
[2025-05-03T04:58:21.567+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (3.17.0)
[2025-05-03T04:58:21.609+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (1.2.14)
[2025-05-03T04:58:21.617+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (0.43b0)
[2025-05-03T04:58:21.657+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venv5k1nx6tc/requirements.txt (line 1)) (1.16.0)
[2025-05-03T04:58:21.680+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (3.3.2)
[2025-05-03T04:58:21.681+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (3.6)
[2025-05-03T04:58:21.681+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (2023.11.17)
[2025-05-03T04:58:21.759+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (1.16.0)
[2025-05-03T04:58:21.766+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (5.0.2)
[2025-05-03T04:58:21.782+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (0.3.0)
[2025-05-03T04:58:21.783+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (4.9)
[2025-05-03T04:58:21.824+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv5k1nx6tc/requirements.txt (line 3)) (0.5.1)
[2025-05-03T04:58:21.874+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-03T04:58:21.898+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 18.5 MB/s eta 0:00:00
[2025-05-03T04:58:24.171+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-03T04:58:24.454+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-03T04:58:24.567+0000] {process_utils.py:190} INFO - 
[2025-05-03T04:58:24.568+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-03T04:58:24.569+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-03T04:58:24.787+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv5k1nx6tc/bin/python /tmp/venv-call6cmr6q6s/script.py /tmp/venv-call6cmr6q6s/script.in /tmp/venv-call6cmr6q6s/script.out /tmp/venv-call6cmr6q6s/string_args.txt /tmp/venv-call6cmr6q6s/termination.log
[2025-05-03T04:58:24.798+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T04:58:25.479+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-03T04:58:26.772+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:26.771+0000[0m] {[34mscript.py:[0m61} INFO[0m - Loading dataset from S3/Minio[0m
[2025-05-03T04:58:26.783+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:26.783+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T04:58:26.898+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:26.897+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T04:58:26.980+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:26.979+0000[0m] {[34mscript.py:[0m69} INFO[0m - Dataset loaded successfully from s3://data/raw/stroke_data.csv[0m
[2025-05-03T04:58:26.988+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:26.980+0000[0m] {[34mscript.py:[0m70} INFO[0m - Dataset shape: (5110, 12)[0m
[2025-05-03T04:58:26.988+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:26.980+0000[0m] {[34mscript.py:[0m71} INFO[0m - Dataset columns: ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke'][0m
[2025-05-03T04:58:26.989+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:26.980+0000[0m] {[34mscript.py:[0m77} INFO[0m - Limpiando datos eliminando duplicados y manejando valores nulos[0m
[2025-05-03T04:58:26.991+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:26.986+0000[0m] {[34mscript.py:[0m85} INFO[0m - Removed 0 duplicate rows[0m
[2025-05-03T04:58:26.991+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:26.988+0000[0m] {[34mscript.py:[0m91} INFO[0m - Imputed 0 null values in 'bmi' column with median value[0m
[2025-05-03T04:58:26.992+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:26.989+0000[0m] {[34mscript.py:[0m104} INFO[0m - No null values remaining in the dataset[0m
[2025-05-03T04:58:26.992+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:26.989+0000[0m] {[34mscript.py:[0m107} INFO[0m - Iniciando ingeniería de características[0m
[2025-05-03T04:58:26.993+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:26.989+0000[0m] {[34mscript.py:[0m55} INFO[0m - Applying One-Hot Encoding to columns: ['gender', 'ever_married', 'work_type', 'residence_type', 'smoking_status'][0m
[2025-05-03T04:58:26.995+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:26.995+0000[0m] {[34mscript.py:[0m114} INFO[0m - Applied one-hot encoding to categorical features[0m
[2025-05-03T04:58:26.996+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:26.996+0000[0m] {[34mscript.py:[0m121} INFO[0m - Removed 'id' column as it's not relevant for prediction[0m
[2025-05-03T04:58:26.998+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:26.998+0000[0m] {[34mscript.py:[0m133} INFO[0m - Truncated 0 extreme values in 'age' column at 82.0[0m
[2025-05-03T04:58:26.999+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:26.999+0000[0m] {[34mscript.py:[0m133} INFO[0m - Truncated 52 extreme values in 'avg_glucose_level' column at 240.7082[0m
[2025-05-03T04:58:27.000+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.000+0000[0m] {[34mscript.py:[0m133} INFO[0m - Truncated 5 extreme values in 'bmi' column at 66.6[0m
[2025-05-03T04:58:27.000+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.000+0000[0m] {[34mscript.py:[0m135} INFO[0m - Feature engineering completed[0m
[2025-05-03T04:58:27.000+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.000+0000[0m] {[34mscript.py:[0m138} INFO[0m - Saving processed dataset to s3://data/processed/stroke_data.csv[0m
[2025-05-03T04:58:27.009+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.008+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T04:58:27.059+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.059+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T04:58:27.092+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.091+0000[0m] {[34mscript.py:[0m142} INFO[0m - Processed dataset saved successfully to s3://data/processed/stroke_data.csv[0m
[2025-05-03T04:58:27.092+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.092+0000[0m] {[34mscript.py:[0m148} INFO[0m - Updating dataset information in S3/Minio[0m
[2025-05-03T04:58:27.098+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.098+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T04:58:27.151+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.151+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T04:58:27.162+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.162+0000[0m] {[34mscript.py:[0m163} INFO[0m - No existing dataset information found, initializing new info dictionary[0m
[2025-05-03T04:58:27.165+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.165+0000[0m] {[34mscript.py:[0m178} INFO[0m - Target column for dataset: log_cnt[0m
[2025-05-03T04:58:27.166+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.166+0000[0m] {[34mscript.py:[0m182} ERROR[0m - Target column 'log_cnt' not found in DataFrame. Available columns: ['age', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi', 'stroke', 'gender_Male', 'gender_Other', 'ever_married_Yes', 'work_type_Never_worked', 'work_type_Private', 'work_type_Self-employed', 'work_type_children', 'residence_type_Urban', 'smoking_status_formerly smoked', 'smoking_status_never smoked', 'smoking_status_smokes'][0m
[2025-05-03T04:58:27.168+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.168+0000[0m] {[34mvariable.py:[0m245} WARNING[0m - The variable target_col is defined in the LocalFilesystemBackend secrets backend, which takes precedence over reading from the database. The value in the database will be updated, but to read it you have to delete the conflicting variable from LocalFilesystemBackend[0m
[2025-05-03T04:58:27.535+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.534+0000[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2025-05-03T04:58:27.538+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.538+0000[0m] {[34mscript.py:[0m186} INFO[0m - Setting target column to default value: stroke[0m
[2025-05-03T04:58:27.548+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.547+0000[0m] {[34mscript.py:[0m216} INFO[0m - Dataset information updated successfully in S3/Minio[0m
[2025-05-03T04:58:27.548+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.548+0000[0m] {[34mscript.py:[0m222} INFO[0m - Logging data to MLflow[0m
[2025-05-03T04:58:27.871+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/data/dataset_source_registry.py:149 UserWarning: Failed to determine whether UCVolumeDatasetSource can resolve source information for 'local file: healthcare-dataset-stroke-data.csv'. Exception:
[2025-05-03T04:58:27.872+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/data/dataset_source_registry.py:149 UserWarning: The specified dataset source can be interpreted in multiple ways: LocalArtifactDatasetSource, LocalArtifactDatasetSource. MLflow will assume that this is a LocalArtifactDatasetSource source.
[2025-05-03T04:58:27.914+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/types/utils.py:407 UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
[2025-05-03T04:58:27.935+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.935+0000[0m] {[34mscript.py:[0m271} INFO[0m - Dataset logged to MLflow successfully in run: feature_engineering_20250503_045827[0m
[2025-05-03T04:58:27.955+0000] {process_utils.py:190} INFO - 2025/05/03 04:58:27 INFO mlflow.tracking._tracking_service.client: 🏃 View run feature_engineering_20250503_045827 at: http://mlflow:5000/#/experiments/1/runs/4ef5706f42244bfaa8d6b2febf894c08.
[2025-05-03T04:58:27.955+0000] {process_utils.py:190} INFO - 2025/05/03 04:58:27 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-03T04:58:27.969+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:27.969+0000[0m] {[34mscript.py:[0m273} INFO[0m - MLflow run ended[0m
[2025-05-03T04:58:28.376+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-03T04:58:28.390+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=feature_engineering, execution_date=20250502T000000, start_date=20250503T045818, end_date=20250503T045828
[2025-05-03T04:58:28.442+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-03T04:58:28.462+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-03T13:44:16.622+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.feature_engineering scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T13:44:16.629+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.feature_engineering scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T13:44:16.630+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-03T13:44:16.642+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): feature_engineering> on 2025-05-02 00:00:00+00:00
[2025-05-03T13:44:16.651+0000] {standard_task_runner.py:60} INFO - Started process 690 to run task
[2025-05-03T13:44:16.656+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'feature_engineering', 'scheduled__2025-05-02T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmp8i6x0ntd']
[2025-05-03T13:44:16.660+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask feature_engineering
[2025-05-03T13:44:16.710+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.feature_engineering scheduled__2025-05-02T00:00:00+00:00 [running]> on host 8fb4c1e7dfa6
[2025-05-03T13:44:16.799+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='feature_engineering' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-02T00:00:00+00:00'
[2025-05-03T13:44:16.803+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvul4l5b8v --system-site-packages --python=python
[2025-05-03T13:44:16.814+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T13:44:17.501+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 377ms
[2025-05-03T13:44:17.502+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvul4l5b8v, clear=False, no_vcs_ignore=False, global=True)
[2025-05-03T13:44:17.502+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmps0ymh78a)
[2025-05-03T13:44:17.502+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-03T13:44:17.503+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-03T13:44:17.532+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvul4l5b8v/bin/pip install -r /tmp/venvul4l5b8v/requirements.txt
[2025-05-03T13:44:17.540+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T13:44:18.190+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-03T13:44:18.402+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venvul4l5b8v/requirements.txt (line 1))
[2025-05-03T13:44:18.441+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-03T13:44:18.443+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvul4l5b8v/requirements.txt (line 2)) (1.37.38)
[2025-05-03T13:44:18.444+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvul4l5b8v/requirements.txt (line 3)) (2.17.2)
[2025-05-03T13:44:18.478+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvul4l5b8v/requirements.txt (line 1)) (1.37.38)
[2025-05-03T13:44:18.480+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvul4l5b8v/requirements.txt (line 1)) (1.24.4)
[2025-05-03T13:44:18.480+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvul4l5b8v/requirements.txt (line 1)) (23.2)
[2025-05-03T13:44:18.482+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvul4l5b8v/requirements.txt (line 1)) (2.0.3)
[2025-05-03T13:44:18.482+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvul4l5b8v/requirements.txt (line 1)) (14.0.2)
[2025-05-03T13:44:18.483+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvul4l5b8v/requirements.txt (line 1)) (4.9.0)
[2025-05-03T13:44:18.487+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venvul4l5b8v/requirements.txt (line 2)) (0.10.0)
[2025-05-03T13:44:18.488+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venvul4l5b8v/requirements.txt (line 2)) (0.11.5)
[2025-05-03T13:44:18.531+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (2.17.2)
[2025-05-03T13:44:18.532+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (2.2.5)
[2025-05-03T13:44:18.533+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (1.13.1)
[2025-05-03T13:44:18.533+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (7.0.0)
[2025-05-03T13:44:18.534+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (3.4.3)
[2025-05-03T13:44:18.534+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (3.5.2)
[2025-05-03T13:44:18.534+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (3.7.5)
[2025-05-03T13:44:18.535+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (1.3.2)
[2025-05-03T13:44:18.536+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (1.10.1)
[2025-05-03T13:44:18.536+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (1.4.51)
[2025-05-03T13:44:18.537+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (3.1.3)
[2025-05-03T13:44:18.538+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (21.2.0)
[2025-05-03T13:44:18.576+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (5.3.2)
[2025-05-03T13:44:18.577+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (8.1.7)
[2025-05-03T13:44:18.578+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (3.1.1)
[2025-05-03T13:44:18.578+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (0.51.0)
[2025-05-03T13:44:18.579+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (3.1.44)
[2025-05-03T13:44:18.579+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (6.11.0)
[2025-05-03T13:44:18.580+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (1.22.0)
[2025-05-03T13:44:18.580+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (1.22.0)
[2025-05-03T13:44:18.581+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (4.25.2)
[2025-05-03T13:44:18.581+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (6.0.1)
[2025-05-03T13:44:18.581+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (2.31.0)
[2025-05-03T13:44:18.582+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (0.4.4)
[2025-05-03T13:44:18.587+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (1.3.0)
[2025-05-03T13:44:18.588+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (5.13.0)
[2025-05-03T13:44:18.594+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvul4l5b8v/requirements.txt (line 1)) (2.8.2)
[2025-05-03T13:44:18.595+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvul4l5b8v/requirements.txt (line 1)) (1.26.18)
[2025-05-03T13:44:18.607+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (2.2.3)
[2025-05-03T13:44:18.608+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (2.1.2)
[2025-05-03T13:44:18.622+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (3.2.6)
[2025-05-03T13:44:18.623+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (3.2.0)
[2025-05-03T13:44:18.631+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (2.1.3)
[2025-05-03T13:44:18.661+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (1.1.1)
[2025-05-03T13:44:18.664+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (0.12.1)
[2025-05-03T13:44:18.665+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (4.57.0)
[2025-05-03T13:44:18.665+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (1.4.7)
[2025-05-03T13:44:18.666+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (10.4.0)
[2025-05-03T13:44:18.666+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (3.1.1)
[2025-05-03T13:44:18.742+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvul4l5b8v/requirements.txt (line 1)) (2023.3.post1)
[2025-05-03T13:44:18.743+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvul4l5b8v/requirements.txt (line 1)) (2023.4)
[2025-05-03T13:44:18.777+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (1.4.2)
[2025-05-03T13:44:18.778+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (3.5.0)
[2025-05-03T13:44:18.851+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (3.0.3)
[2025-05-03T13:44:18.904+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (2.26.2)
[2025-05-03T13:44:18.955+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (4.0.12)
[2025-05-03T13:44:18.991+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (3.17.0)
[2025-05-03T13:44:19.028+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (1.2.14)
[2025-05-03T13:44:19.035+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (0.43b0)
[2025-05-03T13:44:19.071+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvul4l5b8v/requirements.txt (line 1)) (1.16.0)
[2025-05-03T13:44:19.090+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (3.3.2)
[2025-05-03T13:44:19.091+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (3.6)
[2025-05-03T13:44:19.092+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (2023.11.17)
[2025-05-03T13:44:19.163+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (1.16.0)
[2025-05-03T13:44:19.170+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (5.0.2)
[2025-05-03T13:44:19.188+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (0.3.0)
[2025-05-03T13:44:19.189+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (4.9)
[2025-05-03T13:44:19.224+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvul4l5b8v/requirements.txt (line 3)) (0.5.1)
[2025-05-03T13:44:19.263+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-03T13:44:19.281+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 23.5 MB/s eta 0:00:00
[2025-05-03T13:44:21.524+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-03T13:44:21.755+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-03T13:44:21.857+0000] {process_utils.py:190} INFO - 
[2025-05-03T13:44:21.858+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-03T13:44:21.858+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-03T13:44:22.048+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvul4l5b8v/bin/python /tmp/venv-call4jebmb_6/script.py /tmp/venv-call4jebmb_6/script.in /tmp/venv-call4jebmb_6/script.out /tmp/venv-call4jebmb_6/string_args.txt /tmp/venv-call4jebmb_6/termination.log
[2025-05-03T13:44:22.060+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T13:44:22.803+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-03T13:44:24.365+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.364+0000[0m] {[34mscript.py:[0m61} INFO[0m - Loading dataset from S3/Minio[0m
[2025-05-03T13:44:24.376+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.375+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T13:44:24.523+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.522+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T13:44:24.952+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.951+0000[0m] {[34mscript.py:[0m69} INFO[0m - Dataset loaded successfully from s3://data/raw/stroke_data.csv[0m
[2025-05-03T13:44:24.952+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.952+0000[0m] {[34mscript.py:[0m70} INFO[0m - Dataset shape: (5110, 12)[0m
[2025-05-03T13:44:24.953+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.952+0000[0m] {[34mscript.py:[0m71} INFO[0m - Dataset columns: ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke'][0m
[2025-05-03T13:44:24.953+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.952+0000[0m] {[34mscript.py:[0m77} INFO[0m - Limpiando datos eliminando duplicados y manejando valores nulos[0m
[2025-05-03T13:44:24.957+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.957+0000[0m] {[34mscript.py:[0m85} INFO[0m - Removed 0 duplicate rows[0m
[2025-05-03T13:44:24.959+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.959+0000[0m] {[34mscript.py:[0m91} INFO[0m - Imputed 0 null values in 'bmi' column with median value[0m
[2025-05-03T13:44:24.960+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.960+0000[0m] {[34mscript.py:[0m104} INFO[0m - No null values remaining in the dataset[0m
[2025-05-03T13:44:24.961+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.960+0000[0m] {[34mscript.py:[0m107} INFO[0m - Iniciando ingeniería de características[0m
[2025-05-03T13:44:24.961+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.960+0000[0m] {[34mscript.py:[0m55} INFO[0m - Applying One-Hot Encoding to columns: ['gender', 'ever_married', 'work_type', 'residence_type', 'smoking_status'][0m
[2025-05-03T13:44:24.966+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.965+0000[0m] {[34mscript.py:[0m114} INFO[0m - Applied one-hot encoding to categorical features[0m
[2025-05-03T13:44:24.966+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.966+0000[0m] {[34mscript.py:[0m121} INFO[0m - Removed 'id' column as it's not relevant for prediction[0m
[2025-05-03T13:44:24.978+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.978+0000[0m] {[34mscript.py:[0m133} INFO[0m - Truncated 0 extreme values in 'age' column at 82.0[0m
[2025-05-03T13:44:24.980+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.980+0000[0m] {[34mscript.py:[0m133} INFO[0m - Truncated 52 extreme values in 'avg_glucose_level' column at 240.7082[0m
[2025-05-03T13:44:24.981+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.981+0000[0m] {[34mscript.py:[0m133} INFO[0m - Truncated 5 extreme values in 'bmi' column at 66.6[0m
[2025-05-03T13:44:24.982+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.981+0000[0m] {[34mscript.py:[0m135} INFO[0m - Feature engineering completed[0m
[2025-05-03T13:44:24.982+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.981+0000[0m] {[34mscript.py:[0m138} INFO[0m - Saving processed dataset to s3://data/processed/stroke_data.csv[0m
[2025-05-03T13:44:24.992+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:24.991+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T13:44:25.119+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:25.119+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T13:44:25.170+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:25.170+0000[0m] {[34mscript.py:[0m142} INFO[0m - Processed dataset saved successfully to s3://data/processed/stroke_data.csv[0m
[2025-05-03T13:44:25.171+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:25.170+0000[0m] {[34mscript.py:[0m148} INFO[0m - Updating dataset information in S3/Minio[0m
[2025-05-03T13:44:25.181+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:25.180+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T13:44:25.318+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:25.317+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T13:44:25.337+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:25.336+0000[0m] {[34mscript.py:[0m163} INFO[0m - No existing dataset information found, initializing new info dictionary[0m
[2025-05-03T13:44:25.342+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:25.342+0000[0m] {[34mscript.py:[0m178} INFO[0m - Target column for dataset: log_cnt[0m
[2025-05-03T13:44:25.343+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:25.342+0000[0m] {[34mscript.py:[0m182} ERROR[0m - Target column 'log_cnt' not found in DataFrame. Available columns: ['age', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi', 'stroke', 'gender_Male', 'gender_Other', 'ever_married_Yes', 'work_type_Never_worked', 'work_type_Private', 'work_type_Self-employed', 'work_type_children', 'residence_type_Urban', 'smoking_status_formerly smoked', 'smoking_status_never smoked', 'smoking_status_smokes'][0m
[2025-05-03T13:44:25.349+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:25.348+0000[0m] {[34mvariable.py:[0m245} WARNING[0m - The variable target_col is defined in the LocalFilesystemBackend secrets backend, which takes precedence over reading from the database. The value in the database will be updated, but to read it you have to delete the conflicting variable from LocalFilesystemBackend[0m
[2025-05-03T13:44:25.702+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:25.702+0000[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2025-05-03T13:44:25.706+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:25.705+0000[0m] {[34mscript.py:[0m186} INFO[0m - Setting target column to default value: stroke[0m
[2025-05-03T13:44:25.712+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:25.712+0000[0m] {[34mscript.py:[0m216} INFO[0m - Dataset information updated successfully in S3/Minio[0m
[2025-05-03T13:44:25.713+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:25.712+0000[0m] {[34mscript.py:[0m222} INFO[0m - Logging data to MLflow[0m
[2025-05-03T13:44:26.155+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/data/dataset_source_registry.py:149 UserWarning: Failed to determine whether UCVolumeDatasetSource can resolve source information for 'local file: healthcare-dataset-stroke-data.csv'. Exception:
[2025-05-03T13:44:26.156+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/data/dataset_source_registry.py:149 UserWarning: The specified dataset source can be interpreted in multiple ways: LocalArtifactDatasetSource, LocalArtifactDatasetSource. MLflow will assume that this is a LocalArtifactDatasetSource source.
[2025-05-03T13:44:26.198+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/types/utils.py:407 UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
[2025-05-03T13:44:26.250+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:26.250+0000[0m] {[34mscript.py:[0m271} INFO[0m - Dataset logged to MLflow successfully in run: feature_engineering_20250503_134425[0m
[2025-05-03T13:44:26.300+0000] {process_utils.py:190} INFO - 2025/05/03 13:44:26 INFO mlflow.tracking._tracking_service.client: 🏃 View run feature_engineering_20250503_134425 at: http://mlflow:5000/#/experiments/1/runs/da788c721fe444a281ba1317f7b82cb0.
[2025-05-03T13:44:26.300+0000] {process_utils.py:190} INFO - 2025/05/03 13:44:26 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-03T13:44:26.322+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:26.321+0000[0m] {[34mscript.py:[0m273} INFO[0m - MLflow run ended[0m
[2025-05-03T13:44:26.772+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-03T13:44:26.782+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=feature_engineering, execution_date=20250502T000000, start_date=20250503T134416, end_date=20250503T134426
[2025-05-03T13:44:26.823+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-03T13:44:26.845+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-03T18:02:16.401+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.feature_engineering scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T18:02:16.408+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.feature_engineering scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T18:02:16.409+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-03T18:02:16.419+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): feature_engineering> on 2025-05-02 00:00:00+00:00
[2025-05-03T18:02:16.424+0000] {standard_task_runner.py:60} INFO - Started process 740 to run task
[2025-05-03T18:02:16.426+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'feature_engineering', 'scheduled__2025-05-02T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmpqditk71v']
[2025-05-03T18:02:16.428+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask feature_engineering
[2025-05-03T18:02:16.466+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.feature_engineering scheduled__2025-05-02T00:00:00+00:00 [running]> on host 2042e9a26c53
[2025-05-03T18:02:16.527+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='feature_engineering' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-02T00:00:00+00:00'
[2025-05-03T18:02:16.532+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvhc20ufmq --system-site-packages --python=python
[2025-05-03T18:02:16.538+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T18:02:17.101+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 288ms
[2025-05-03T18:02:17.101+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvhc20ufmq, clear=False, no_vcs_ignore=False, global=True)
[2025-05-03T18:02:17.102+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmprrkobqz3)
[2025-05-03T18:02:17.102+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-03T18:02:17.102+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-03T18:02:17.122+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvhc20ufmq/bin/pip install -r /tmp/venvhc20ufmq/requirements.txt
[2025-05-03T18:02:17.128+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T18:02:17.734+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-03T18:02:17.958+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venvhc20ufmq/requirements.txt (line 1))
[2025-05-03T18:02:17.994+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-03T18:02:17.995+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvhc20ufmq/requirements.txt (line 2)) (1.37.38)
[2025-05-03T18:02:17.996+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvhc20ufmq/requirements.txt (line 3)) (2.17.2)
[2025-05-03T18:02:18.028+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvhc20ufmq/requirements.txt (line 1)) (1.37.38)
[2025-05-03T18:02:18.029+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvhc20ufmq/requirements.txt (line 1)) (1.24.4)
[2025-05-03T18:02:18.030+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvhc20ufmq/requirements.txt (line 1)) (23.2)
[2025-05-03T18:02:18.031+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvhc20ufmq/requirements.txt (line 1)) (2.0.3)
[2025-05-03T18:02:18.031+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvhc20ufmq/requirements.txt (line 1)) (14.0.2)
[2025-05-03T18:02:18.032+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvhc20ufmq/requirements.txt (line 1)) (4.9.0)
[2025-05-03T18:02:18.036+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venvhc20ufmq/requirements.txt (line 2)) (0.10.0)
[2025-05-03T18:02:18.036+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3->-r /tmp/venvhc20ufmq/requirements.txt (line 2)) (0.11.5)
[2025-05-03T18:02:18.073+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (2.17.2)
[2025-05-03T18:02:18.074+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (2.2.5)
[2025-05-03T18:02:18.074+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (1.13.1)
[2025-05-03T18:02:18.075+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (7.0.0)
[2025-05-03T18:02:18.076+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (3.4.3)
[2025-05-03T18:02:18.076+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (3.5.2)
[2025-05-03T18:02:18.077+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (3.7.5)
[2025-05-03T18:02:18.077+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (1.3.2)
[2025-05-03T18:02:18.077+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (1.10.1)
[2025-05-03T18:02:18.078+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (1.4.51)
[2025-05-03T18:02:18.078+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (3.1.3)
[2025-05-03T18:02:18.079+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (21.2.0)
[2025-05-03T18:02:18.109+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (5.3.2)
[2025-05-03T18:02:18.110+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (8.1.7)
[2025-05-03T18:02:18.111+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (3.1.1)
[2025-05-03T18:02:18.111+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (0.51.0)
[2025-05-03T18:02:18.112+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (3.1.44)
[2025-05-03T18:02:18.112+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (6.11.0)
[2025-05-03T18:02:18.113+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (1.22.0)
[2025-05-03T18:02:18.113+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (1.22.0)
[2025-05-03T18:02:18.114+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (4.25.2)
[2025-05-03T18:02:18.115+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (6.0.1)
[2025-05-03T18:02:18.115+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (2.31.0)
[2025-05-03T18:02:18.116+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (0.4.4)
[2025-05-03T18:02:18.121+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (1.3.0)
[2025-05-03T18:02:18.122+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (5.13.0)
[2025-05-03T18:02:18.128+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvhc20ufmq/requirements.txt (line 1)) (2.8.2)
[2025-05-03T18:02:18.130+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvhc20ufmq/requirements.txt (line 1)) (1.26.18)
[2025-05-03T18:02:18.139+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (2.2.3)
[2025-05-03T18:02:18.140+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (2.1.2)
[2025-05-03T18:02:18.153+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (3.2.6)
[2025-05-03T18:02:18.153+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (3.2.0)
[2025-05-03T18:02:18.160+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (2.1.3)
[2025-05-03T18:02:18.188+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (1.1.1)
[2025-05-03T18:02:18.189+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (0.12.1)
[2025-05-03T18:02:18.190+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (4.57.0)
[2025-05-03T18:02:18.190+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (1.4.7)
[2025-05-03T18:02:18.191+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (10.4.0)
[2025-05-03T18:02:18.192+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (3.1.1)
[2025-05-03T18:02:18.252+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvhc20ufmq/requirements.txt (line 1)) (2023.3.post1)
[2025-05-03T18:02:18.253+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvhc20ufmq/requirements.txt (line 1)) (2023.4)
[2025-05-03T18:02:18.283+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (1.4.2)
[2025-05-03T18:02:18.284+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (3.5.0)
[2025-05-03T18:02:18.345+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (3.0.3)
[2025-05-03T18:02:18.393+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (2.26.2)
[2025-05-03T18:02:18.437+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (4.0.12)
[2025-05-03T18:02:18.482+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (3.17.0)
[2025-05-03T18:02:18.513+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (1.2.14)
[2025-05-03T18:02:18.519+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (0.43b0)
[2025-05-03T18:02:18.551+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvhc20ufmq/requirements.txt (line 1)) (1.16.0)
[2025-05-03T18:02:18.569+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (3.3.2)
[2025-05-03T18:02:18.569+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (3.6)
[2025-05-03T18:02:18.570+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (2023.11.17)
[2025-05-03T18:02:18.628+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (1.16.0)
[2025-05-03T18:02:18.634+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (5.0.2)
[2025-05-03T18:02:18.646+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (0.3.0)
[2025-05-03T18:02:18.647+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (4.9)
[2025-05-03T18:02:18.678+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvhc20ufmq/requirements.txt (line 3)) (0.5.1)
[2025-05-03T18:02:18.712+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-03T18:02:18.739+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 15.3 MB/s eta 0:00:00
[2025-05-03T18:02:20.444+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-03T18:02:20.628+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-03T18:02:20.727+0000] {process_utils.py:190} INFO - 
[2025-05-03T18:02:20.729+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-03T18:02:20.730+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-03T18:02:20.849+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvhc20ufmq/bin/python /tmp/venv-callayxr7em3/script.py /tmp/venv-callayxr7em3/script.in /tmp/venv-callayxr7em3/script.out /tmp/venv-callayxr7em3/string_args.txt /tmp/venv-callayxr7em3/termination.log
[2025-05-03T18:02:20.854+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T18:02:21.385+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-03T18:02:22.647+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.644+0000[0m] {[34mscript.py:[0m61} INFO[0m - Loading dataset from S3/Minio[0m
[2025-05-03T18:02:22.658+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.657+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T18:02:22.765+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.764+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T18:02:22.814+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.813+0000[0m] {[34mscript.py:[0m69} INFO[0m - Dataset loaded successfully from s3://data/raw/stroke_data.csv[0m
[2025-05-03T18:02:22.815+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.814+0000[0m] {[34mscript.py:[0m70} INFO[0m - Dataset shape: (5110, 12)[0m
[2025-05-03T18:02:22.815+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.814+0000[0m] {[34mscript.py:[0m71} INFO[0m - Dataset columns: ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke'][0m
[2025-05-03T18:02:22.816+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.814+0000[0m] {[34mscript.py:[0m77} INFO[0m - Limpiando datos eliminando duplicados y manejando valores nulos[0m
[2025-05-03T18:02:22.819+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.819+0000[0m] {[34mscript.py:[0m85} INFO[0m - Removed 0 duplicate rows[0m
[2025-05-03T18:02:22.821+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.821+0000[0m] {[34mscript.py:[0m91} INFO[0m - Imputed 0 null values in 'bmi' column with median value[0m
[2025-05-03T18:02:22.822+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.822+0000[0m] {[34mscript.py:[0m104} INFO[0m - No null values remaining in the dataset[0m
[2025-05-03T18:02:22.822+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.822+0000[0m] {[34mscript.py:[0m107} INFO[0m - Iniciando ingeniería de características[0m
[2025-05-03T18:02:22.823+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.822+0000[0m] {[34mscript.py:[0m55} INFO[0m - Applying One-Hot Encoding to columns: ['gender', 'ever_married', 'work_type', 'residence_type', 'smoking_status'][0m
[2025-05-03T18:02:22.826+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.826+0000[0m] {[34mscript.py:[0m114} INFO[0m - Applied one-hot encoding to categorical features[0m
[2025-05-03T18:02:22.827+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.827+0000[0m] {[34mscript.py:[0m121} INFO[0m - Removed 'id' column as it's not relevant for prediction[0m
[2025-05-03T18:02:22.828+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.828+0000[0m] {[34mscript.py:[0m133} INFO[0m - Truncated 0 extreme values in 'age' column at 82.0[0m
[2025-05-03T18:02:22.830+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.829+0000[0m] {[34mscript.py:[0m133} INFO[0m - Truncated 52 extreme values in 'avg_glucose_level' column at 240.7082[0m
[2025-05-03T18:02:22.831+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.831+0000[0m] {[34mscript.py:[0m133} INFO[0m - Truncated 5 extreme values in 'bmi' column at 66.6[0m
[2025-05-03T18:02:22.831+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.831+0000[0m] {[34mscript.py:[0m135} INFO[0m - Feature engineering completed[0m
[2025-05-03T18:02:22.832+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.831+0000[0m] {[34mscript.py:[0m138} INFO[0m - Saving processed dataset to s3://data/processed/stroke_data.csv[0m
[2025-05-03T18:02:22.837+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.837+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T18:02:22.888+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.888+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T18:02:22.922+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.921+0000[0m] {[34mscript.py:[0m142} INFO[0m - Processed dataset saved successfully to s3://data/processed/stroke_data.csv[0m
[2025-05-03T18:02:22.922+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.922+0000[0m] {[34mscript.py:[0m148} INFO[0m - Updating dataset information in S3/Minio[0m
[2025-05-03T18:02:22.928+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.928+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T18:02:22.975+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.974+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T18:02:22.983+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.983+0000[0m] {[34mscript.py:[0m163} INFO[0m - No existing dataset information found, initializing new info dictionary[0m
[2025-05-03T18:02:22.987+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.986+0000[0m] {[34mscript.py:[0m178} INFO[0m - Target column for dataset: log_cnt[0m
[2025-05-03T18:02:22.987+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.987+0000[0m] {[34mscript.py:[0m182} ERROR[0m - Target column 'log_cnt' not found in DataFrame. Available columns: ['age', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi', 'stroke', 'gender_Male', 'gender_Other', 'ever_married_Yes', 'work_type_Never_worked', 'work_type_Private', 'work_type_Self-employed', 'work_type_children', 'residence_type_Urban', 'smoking_status_formerly smoked', 'smoking_status_never smoked', 'smoking_status_smokes'][0m
[2025-05-03T18:02:22.991+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:22.991+0000[0m] {[34mvariable.py:[0m245} WARNING[0m - The variable target_col is defined in the LocalFilesystemBackend secrets backend, which takes precedence over reading from the database. The value in the database will be updated, but to read it you have to delete the conflicting variable from LocalFilesystemBackend[0m
[2025-05-03T18:02:23.322+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:23.321+0000[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2025-05-03T18:02:23.326+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:23.325+0000[0m] {[34mscript.py:[0m186} INFO[0m - Setting target column to default value: stroke[0m
[2025-05-03T18:02:23.333+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:23.333+0000[0m] {[34mscript.py:[0m216} INFO[0m - Dataset information updated successfully in S3/Minio[0m
[2025-05-03T18:02:23.334+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:23.333+0000[0m] {[34mscript.py:[0m222} INFO[0m - Logging data to MLflow[0m
[2025-05-03T18:02:24.664+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/data/dataset_source_registry.py:149 UserWarning: Failed to determine whether UCVolumeDatasetSource can resolve source information for 'local file: healthcare-dataset-stroke-data.csv'. Exception:
[2025-05-03T18:02:24.665+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/data/dataset_source_registry.py:149 UserWarning: The specified dataset source can be interpreted in multiple ways: LocalArtifactDatasetSource, LocalArtifactDatasetSource. MLflow will assume that this is a LocalArtifactDatasetSource source.
[2025-05-03T18:02:24.710+0000] {process_utils.py:190} INFO - /home/***/.local/lib/python3.8/site-packages/mlflow/types/utils.py:407 UserWarning: Hint: Inferred schema contains integer column(s). Integer columns in Python cannot represent missing values. If your input data contains missing values at inference time, it will be encoded as floats and will cause a schema enforcement error. The best way to avoid this problem is to infer the model schema based on a realistic data sample (training dataset) that includes missing values. Alternatively, you can declare integer columns as doubles (float64) whenever these columns may have missing values. See `Handling Integers With Missing Values <https://www.mlflow.org/docs/latest/models.html#handling-integers-with-missing-values>`_ for more details.
[2025-05-03T18:02:24.740+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:24.739+0000[0m] {[34mscript.py:[0m271} INFO[0m - Dataset logged to MLflow successfully in run: feature_engineering_20250503_180224[0m
[2025-05-03T18:02:24.782+0000] {process_utils.py:190} INFO - 2025/05/03 18:02:24 INFO mlflow.tracking._tracking_service.client: 🏃 View run feature_engineering_20250503_180224 at: http://mlflow:5000/#/experiments/1/runs/28679b5a0670471c99aa7abeef496f12.
[2025-05-03T18:02:24.783+0000] {process_utils.py:190} INFO - 2025/05/03 18:02:24 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-03T18:02:24.809+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:24.809+0000[0m] {[34mscript.py:[0m273} INFO[0m - MLflow run ended[0m
[2025-05-03T18:02:25.193+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-03T18:02:25.202+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=feature_engineering, execution_date=20250502T000000, start_date=20250503T180216, end_date=20250503T180225
[2025-05-03T18:02:25.237+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-03T18:02:25.255+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
