[2025-05-02T16:00:15.156+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data.normalize_data scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T16:00:15.166+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data.normalize_data scheduled__2025-05-01T00:00:00+00:00 [queued]>
[2025-05-02T16:00:15.167+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-02T16:00:15.193+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): normalize_data> on 2025-05-01 00:00:00+00:00
[2025-05-02T16:00:15.206+0000] {standard_task_runner.py:60} INFO - Started process 719 to run task
[2025-05-02T16:00:15.209+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data', 'normalize_data', 'scheduled__2025-05-01T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmpttjb7q3y']
[2025-05-02T16:00:15.211+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask normalize_data
[2025-05-02T16:00:15.295+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data.normalize_data scheduled__2025-05-01T00:00:00+00:00 [running]> on host 936bf26779ff
[2025-05-02T16:00:15.387+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data' AIRFLOW_CTX_TASK_ID='normalize_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T00:00:00+00:00'
[2025-05-02T16:00:15.395+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvf9r8atkq --system-site-packages --python=python
[2025-05-02T16:00:15.409+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T16:00:16.157+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 387ms
[2025-05-02T16:00:16.157+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvf9r8atkq, clear=False, no_vcs_ignore=False, global=True)
[2025-05-02T16:00:16.158+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmp4158inrr)
[2025-05-02T16:00:16.158+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-02T16:00:16.159+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-02T16:00:16.198+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvf9r8atkq/bin/pip install -r /tmp/venvf9r8atkq/requirements.txt
[2025-05-02T16:00:16.207+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T16:00:16.897+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-02T16:00:17.118+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venvf9r8atkq/requirements.txt (line 1))
[2025-05-02T16:00:17.156+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-02T16:00:17.196+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvf9r8atkq/requirements.txt (line 1)) (1.37.38)
[2025-05-02T16:00:17.197+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvf9r8atkq/requirements.txt (line 1)) (1.37.38)
[2025-05-02T16:00:17.198+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvf9r8atkq/requirements.txt (line 1)) (1.24.4)
[2025-05-02T16:00:17.198+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvf9r8atkq/requirements.txt (line 1)) (23.2)
[2025-05-02T16:00:17.199+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas<2.1.0,>=1.2.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvf9r8atkq/requirements.txt (line 1)) (2.0.3)
[2025-05-02T16:00:17.199+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvf9r8atkq/requirements.txt (line 1)) (14.0.2)
[2025-05-02T16:00:17.200+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvf9r8atkq/requirements.txt (line 1)) (4.9.0)
[2025-05-02T16:00:17.204+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvf9r8atkq/requirements.txt (line 1)) (0.10.0)
[2025-05-02T16:00:17.205+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvf9r8atkq/requirements.txt (line 1)) (0.11.5)
[2025-05-02T16:00:17.211+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvf9r8atkq/requirements.txt (line 1)) (2.8.2)
[2025-05-02T16:00:17.212+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvf9r8atkq/requirements.txt (line 1)) (1.26.18)
[2025-05-02T16:00:17.280+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvf9r8atkq/requirements.txt (line 1)) (2023.3.post1)
[2025-05-02T16:00:17.281+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas<2.1.0,>=1.2.0->awswrangler==3.9.1->-r /tmp/venvf9r8atkq/requirements.txt (line 1)) (2023.4)
[2025-05-02T16:00:17.288+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvf9r8atkq/requirements.txt (line 1)) (1.16.0)
[2025-05-02T16:00:17.320+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-02T16:00:17.343+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 18.7 MB/s eta 0:00:00
[2025-05-02T16:00:19.808+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-02T16:00:20.082+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-02T16:00:20.182+0000] {process_utils.py:190} INFO - 
[2025-05-02T16:00:20.183+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-02T16:00:20.183+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-02T16:00:20.510+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvf9r8atkq/bin/python /tmp/venv-call35wwa6wl/script.py /tmp/venv-call35wwa6wl/script.in /tmp/venv-call35wwa6wl/script.out /tmp/venv-call35wwa6wl/string_args.txt /tmp/venv-call35wwa6wl/termination.log
[2025-05-02T16:00:20.526+0000] {process_utils.py:186} INFO - Output:
[2025-05-02T16:00:21.334+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-02T16:00:23.072+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.071+0000[0m] {[34mscript.py:[0m50} INFO[0m - Starting to read training and testing datasets from S3/Minio[0m
[2025-05-02T16:00:23.081+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.081+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T16:00:23.139+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.138+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T16:00:23.182+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.181+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T16:00:23.315+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.314+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T16:00:23.348+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.348+0000[0m] {[34mscript.py:[0m56} INFO[0m - Training and testing datasets loaded successfully from S3/Minio[0m
[2025-05-02T16:00:23.349+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.348+0000[0m] {[34mscript.py:[0m61} INFO[0m - Initializing the StandardScaler[0m
[2025-05-02T16:00:23.352+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.351+0000[0m] {[34mscript.py:[0m70} INFO[0m - Data normalization completed successfully using StandardScaler[0m
[2025-05-02T16:00:23.352+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.352+0000[0m] {[34mscript.py:[0m79} INFO[0m - Scaled data successfully converted to DataFrame[0m
[2025-05-02T16:00:23.353+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.352+0000[0m] {[34mscript.py:[0m84} INFO[0m - Starting to save scaled training and testing datasets to S3/Minio[0m
[2025-05-02T16:00:23.359+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.359+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T16:00:23.406+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.406+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T16:00:23.474+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.473+0000[0m] {[34mscript.py:[0m89} INFO[0m - Scaled training data saved successfully to s3://data/train/stroke_data_X_train_scaled.csv[0m
[2025-05-02T16:00:23.481+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.481+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T16:00:23.531+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.531+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T16:00:23.565+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.565+0000[0m] {[34mscript.py:[0m92} INFO[0m - Scaled testing data saved successfully to s3://data/test/stroke_data_X_test_scaled.csv[0m
[2025-05-02T16:00:23.566+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.565+0000[0m] {[34mscript.py:[0m97} INFO[0m - Updating dataset information with scaler details[0m
[2025-05-02T16:00:23.572+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.572+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-02T16:00:23.743+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.743+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-02T16:00:23.757+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.757+0000[0m] {[34mscript.py:[0m108} INFO[0m - Existing dataset information loaded from S3/Minio[0m
[2025-05-02T16:00:23.764+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.764+0000[0m] {[34mscript.py:[0m127} INFO[0m - Dataset information updated successfully in S3/Minio with scaler details[0m
[2025-05-02T16:00:23.765+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:23.764+0000[0m] {[34mscript.py:[0m132} INFO[0m - Logging scaler details and dataset info to MLflow[0m
[2025-05-02T16:00:24.014+0000] {process_utils.py:190} INFO - 2025/05/02 16:00:24 INFO mlflow.tracking._tracking_service.client: 🏃 View run Normalize_run_2025/05/02-16:00:23 at: http://mlflow:5000/#/experiments/1/runs/efef2ead53934e618e427cf7ee283067.
[2025-05-02T16:00:24.015+0000] {process_utils.py:190} INFO - 2025/05/02 16:00:24 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-02T16:00:24.037+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:24.037+0000[0m] {[34mscript.py:[0m158} INFO[0m - Scaler details and dataset info logged to MLflow successfully[0m
[2025-05-02T16:00:24.038+0000] {process_utils.py:190} INFO - [[34m2025-05-02T16:00:24.037+0000[0m] {[34mscript.py:[0m163} INFO[0m - Data normalization process completed successfully[0m
[2025-05-02T16:00:24.521+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-02T16:00:24.533+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data, task_id=normalize_data, execution_date=20250501T000000, start_date=20250502T160015, end_date=20250502T160024
[2025-05-02T16:00:24.550+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-02T16:00:24.566+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
