[2025-05-03T00:17:38.428+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T00:17:38.435+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T00:17:38.436+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-03T00:17:38.445+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): get_original_data> on 2025-05-02 00:00:00+00:00
[2025-05-03T00:17:38.449+0000] {standard_task_runner.py:60} INFO - Started process 752 to run task
[2025-05-03T00:17:38.452+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'get_original_data', 'scheduled__2025-05-02T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmpmqdby3c0']
[2025-05-03T00:17:38.454+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask get_original_data
[2025-05-03T00:17:38.496+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-02T00:00:00+00:00 [running]> on host b5903f3da971
[2025-05-03T00:17:38.546+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='get_original_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-02T00:00:00+00:00'
[2025-05-03T00:17:38.548+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvt134rjiq --system-site-packages --python=python
[2025-05-03T00:17:38.554+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T00:17:39.275+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 392ms
[2025-05-03T00:17:39.275+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvt134rjiq, clear=False, no_vcs_ignore=False, global=True)
[2025-05-03T00:17:39.276+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmpsqavnc_n)
[2025-05-03T00:17:39.276+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-03T00:17:39.276+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-03T00:17:39.299+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvt134rjiq/bin/pip install -r /tmp/venvt134rjiq/requirements.txt
[2025-05-03T00:17:39.304+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T00:17:39.912+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-03T00:17:40.278+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venvt134rjiq/requirements.txt (line 1))
[2025-05-03T00:17:40.336+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-03T00:17:40.338+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvt134rjiq/requirements.txt (line 2)) (2.17.2)
[2025-05-03T00:17:40.339+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvt134rjiq/requirements.txt (line 3)) (2.0.3)
[2025-05-03T00:17:40.369+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvt134rjiq/requirements.txt (line 1)) (1.37.38)
[2025-05-03T00:17:40.371+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvt134rjiq/requirements.txt (line 1)) (1.37.38)
[2025-05-03T00:17:40.372+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvt134rjiq/requirements.txt (line 1)) (1.24.4)
[2025-05-03T00:17:40.373+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvt134rjiq/requirements.txt (line 1)) (23.2)
[2025-05-03T00:17:40.374+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvt134rjiq/requirements.txt (line 1)) (14.0.2)
[2025-05-03T00:17:40.375+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvt134rjiq/requirements.txt (line 1)) (4.9.0)
[2025-05-03T00:17:40.407+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (2.17.2)
[2025-05-03T00:17:40.407+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (2.2.5)
[2025-05-03T00:17:40.408+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (1.13.1)
[2025-05-03T00:17:40.409+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (7.0.0)
[2025-05-03T00:17:40.410+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (3.4.3)
[2025-05-03T00:17:40.411+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (3.5.2)
[2025-05-03T00:17:40.412+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (3.7.5)
[2025-05-03T00:17:40.412+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (1.3.2)
[2025-05-03T00:17:40.413+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (1.10.1)
[2025-05-03T00:17:40.413+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (1.4.51)
[2025-05-03T00:17:40.414+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (3.1.3)
[2025-05-03T00:17:40.415+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (21.2.0)
[2025-05-03T00:17:40.444+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (5.3.2)
[2025-05-03T00:17:40.445+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (8.1.7)
[2025-05-03T00:17:40.446+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (3.1.1)
[2025-05-03T00:17:40.447+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (0.51.0)
[2025-05-03T00:17:40.448+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (3.1.44)
[2025-05-03T00:17:40.448+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (6.11.0)
[2025-05-03T00:17:40.449+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (1.22.0)
[2025-05-03T00:17:40.450+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (1.22.0)
[2025-05-03T00:17:40.451+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (4.25.2)
[2025-05-03T00:17:40.451+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (6.0.1)
[2025-05-03T00:17:40.452+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (2.31.0)
[2025-05-03T00:17:40.453+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (0.4.4)
[2025-05-03T00:17:40.514+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvt134rjiq/requirements.txt (line 3)) (2.8.2)
[2025-05-03T00:17:40.515+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvt134rjiq/requirements.txt (line 3)) (2023.3.post1)
[2025-05-03T00:17:40.516+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvt134rjiq/requirements.txt (line 3)) (2023.4)
[2025-05-03T00:17:40.532+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (1.3.0)
[2025-05-03T00:17:40.533+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (5.13.0)
[2025-05-03T00:17:40.537+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvt134rjiq/requirements.txt (line 1)) (0.10.0)
[2025-05-03T00:17:40.537+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvt134rjiq/requirements.txt (line 1)) (0.11.5)
[2025-05-03T00:17:40.543+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvt134rjiq/requirements.txt (line 1)) (1.26.18)
[2025-05-03T00:17:40.554+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (2.2.3)
[2025-05-03T00:17:40.555+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (2.1.2)
[2025-05-03T00:17:40.569+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (3.2.6)
[2025-05-03T00:17:40.570+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (3.2.0)
[2025-05-03T00:17:40.578+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (2.1.3)
[2025-05-03T00:17:40.593+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (1.1.1)
[2025-05-03T00:17:40.593+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (0.12.1)
[2025-05-03T00:17:40.594+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (4.57.0)
[2025-05-03T00:17:40.594+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (1.4.7)
[2025-05-03T00:17:40.595+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (10.4.0)
[2025-05-03T00:17:40.596+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (3.1.1)
[2025-05-03T00:17:40.605+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas->-r /tmp/venvt134rjiq/requirements.txt (line 3)) (1.16.0)
[2025-05-03T00:17:40.632+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (1.4.2)
[2025-05-03T00:17:40.633+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (3.5.0)
[2025-05-03T00:17:40.699+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (3.0.3)
[2025-05-03T00:17:40.752+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (2.26.2)
[2025-05-03T00:17:40.795+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (4.0.12)
[2025-05-03T00:17:40.827+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (3.17.0)
[2025-05-03T00:17:40.862+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (1.2.14)
[2025-05-03T00:17:40.868+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (0.43b0)
[2025-05-03T00:17:40.908+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (3.3.2)
[2025-05-03T00:17:40.909+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (3.6)
[2025-05-03T00:17:40.910+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (2023.11.17)
[2025-05-03T00:17:40.978+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (1.16.0)
[2025-05-03T00:17:40.984+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (5.0.2)
[2025-05-03T00:17:40.996+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (0.3.0)
[2025-05-03T00:17:40.997+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (4.9)
[2025-05-03T00:17:41.026+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvt134rjiq/requirements.txt (line 2)) (0.5.1)
[2025-05-03T00:17:41.059+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-03T00:17:41.091+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 13.7 MB/s eta 0:00:00
[2025-05-03T00:17:42.903+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-03T00:17:43.109+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-03T00:17:43.196+0000] {process_utils.py:190} INFO - 
[2025-05-03T00:17:43.197+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-03T00:17:43.197+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-03T00:17:43.319+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvt134rjiq/bin/python /tmp/venv-call0icbvqxy/script.py /tmp/venv-call0icbvqxy/script.in /tmp/venv-call0icbvqxy/script.out /tmp/venv-call0icbvqxy/string_args.txt /tmp/venv-call0icbvqxy/termination.log
[2025-05-03T00:17:43.325+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T00:17:44.057+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-03T00:17:47.087+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:17:47.086+0000[0m] {[34mscript.py:[0m49} INFO[0m - Starting to read the dataset from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-03T00:17:47.121+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:17:47.120+0000[0m] {[34mscript.py:[0m59} INFO[0m - Dataset read successfully from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-03T00:17:47.121+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:17:47.121+0000[0m] {[34mscript.py:[0m60} INFO[0m - Dataset shape: (5110, 12)[0m
[2025-05-03T00:17:47.123+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:17:47.122+0000[0m] {[34mscript.py:[0m76} INFO[0m - Dataset columns: ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke'][0m
[2025-05-03T00:17:47.150+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:17:47.149+0000[0m] {[34mconnectionpool.py:[0m824} WARNING[0m - Retrying (JitteredRetry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81f074db50>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stroke+Prediction[0m
[2025-05-03T00:17:51.154+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:17:51.153+0000[0m] {[34mconnectionpool.py:[0m824} WARNING[0m - Retrying (JitteredRetry(total=3, connect=3, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81f074dd90>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stroke+Prediction[0m
[2025-05-03T00:17:59.164+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:17:59.163+0000[0m] {[34mconnectionpool.py:[0m824} WARNING[0m - Retrying (JitteredRetry(total=2, connect=2, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81f079efd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stroke+Prediction[0m
[2025-05-03T00:18:15.187+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:18:15.184+0000[0m] {[34mconnectionpool.py:[0m824} WARNING[0m - Retrying (JitteredRetry(total=1, connect=1, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81f079ee50>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stroke+Prediction[0m
[2025-05-03T00:18:47.222+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:18:47.220+0000[0m] {[34mconnectionpool.py:[0m824} WARNING[0m - Retrying (JitteredRetry(total=0, connect=0, read=5, redirect=5, status=5)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81f079e970>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stroke+Prediction[0m
[2025-05-03T00:18:47.229+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:18:47.228+0000[0m] {[34mscript.py:[0m109} ERROR[0m - Error al leer el archivo CSV: API request to http://mlflow:5000/api/2.0/mlflow/experiments/get-by-name failed with exception HTTPConnectionPool(host='mlflow', port=5000): Max retries exceeded with url: /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stroke+Prediction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81f079e670>: Failed to establish a new connection: [Errno 111] Connection refused'))[0m
[2025-05-03T00:18:47.238+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2025-05-03T00:18:47.239+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
[2025-05-03T00:18:47.241+0000] {process_utils.py:190} INFO -     conn = connection.create_connection(
[2025-05-03T00:18:47.245+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
[2025-05-03T00:18:47.245+0000] {process_utils.py:190} INFO -     raise err
[2025-05-03T00:18:47.246+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
[2025-05-03T00:18:47.246+0000] {process_utils.py:190} INFO -     sock.connect(sa)
[2025-05-03T00:18:47.246+0000] {process_utils.py:190} INFO - ConnectionRefusedError: [Errno 111] Connection refused
[2025-05-03T00:18:47.246+0000] {process_utils.py:190} INFO - 
[2025-05-03T00:18:47.247+0000] {process_utils.py:190} INFO - During handling of the above exception, another exception occurred:
[2025-05-03T00:18:47.247+0000] {process_utils.py:190} INFO - 
[2025-05-03T00:18:47.247+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2025-05-03T00:18:47.247+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
[2025-05-03T00:18:47.248+0000] {process_utils.py:190} INFO -     httplib_response = self._make_request(
[2025-05-03T00:18:47.248+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 416, in _make_request
[2025-05-03T00:18:47.248+0000] {process_utils.py:190} INFO -     conn.request(method, url, **httplib_request_kw)
[2025-05-03T00:18:47.248+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/urllib3/connection.py", line 244, in request
[2025-05-03T00:18:47.249+0000] {process_utils.py:190} INFO -     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
[2025-05-03T00:18:47.249+0000] {process_utils.py:190} INFO -   File "/usr/local/lib/python3.8/http/client.py", line 1256, in request
[2025-05-03T00:18:47.249+0000] {process_utils.py:190} INFO -     self._send_request(method, url, body, headers, encode_chunked)
[2025-05-03T00:18:47.249+0000] {process_utils.py:190} INFO -   File "/usr/local/lib/python3.8/http/client.py", line 1302, in _send_request
[2025-05-03T00:18:47.249+0000] {process_utils.py:190} INFO -     self.endheaders(body, encode_chunked=encode_chunked)
[2025-05-03T00:18:47.250+0000] {process_utils.py:190} INFO -   File "/usr/local/lib/python3.8/http/client.py", line 1251, in endheaders
[2025-05-03T00:18:47.250+0000] {process_utils.py:190} INFO -     self._send_output(message_body, encode_chunked=encode_chunked)
[2025-05-03T00:18:47.250+0000] {process_utils.py:190} INFO -   File "/usr/local/lib/python3.8/http/client.py", line 1011, in _send_output
[2025-05-03T00:18:47.250+0000] {process_utils.py:190} INFO -     self.send(msg)
[2025-05-03T00:18:47.250+0000] {process_utils.py:190} INFO -   File "/usr/local/lib/python3.8/http/client.py", line 951, in send
[2025-05-03T00:18:47.250+0000] {process_utils.py:190} INFO -     self.connect()
[2025-05-03T00:18:47.251+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
[2025-05-03T00:18:47.251+0000] {process_utils.py:190} INFO -     conn = self._new_conn()
[2025-05-03T00:18:47.252+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
[2025-05-03T00:18:47.252+0000] {process_utils.py:190} INFO -     raise NewConnectionError(
[2025-05-03T00:18:47.252+0000] {process_utils.py:190} INFO - urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f81f079e670>: Failed to establish a new connection: [Errno 111] Connection refused
[2025-05-03T00:18:47.253+0000] {process_utils.py:190} INFO - 
[2025-05-03T00:18:47.253+0000] {process_utils.py:190} INFO - During handling of the above exception, another exception occurred:
[2025-05-03T00:18:47.253+0000] {process_utils.py:190} INFO - 
[2025-05-03T00:18:47.254+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2025-05-03T00:18:47.254+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
[2025-05-03T00:18:47.254+0000] {process_utils.py:190} INFO -     resp = conn.urlopen(
[2025-05-03T00:18:47.254+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 827, in urlopen
[2025-05-03T00:18:47.255+0000] {process_utils.py:190} INFO -     return self.urlopen(
[2025-05-03T00:18:47.255+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 827, in urlopen
[2025-05-03T00:18:47.255+0000] {process_utils.py:190} INFO -     return self.urlopen(
[2025-05-03T00:18:47.255+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 827, in urlopen
[2025-05-03T00:18:47.256+0000] {process_utils.py:190} INFO -     return self.urlopen(
[2025-05-03T00:18:47.256+0000] {process_utils.py:190} INFO -   [Previous line repeated 2 more times]
[2025-05-03T00:18:47.256+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 799, in urlopen
[2025-05-03T00:18:47.256+0000] {process_utils.py:190} INFO -     retries = retries.increment(
[2025-05-03T00:18:47.257+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
[2025-05-03T00:18:47.257+0000] {process_utils.py:190} INFO -     raise MaxRetryError(_pool, url, error or ResponseError(cause))
[2025-05-03T00:18:47.257+0000] {process_utils.py:190} INFO - urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='mlflow', port=5000): Max retries exceeded with url: /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stroke+Prediction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81f079e670>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2025-05-03T00:18:47.257+0000] {process_utils.py:190} INFO - 
[2025-05-03T00:18:47.258+0000] {process_utils.py:190} INFO - During handling of the above exception, another exception occurred:
[2025-05-03T00:18:47.258+0000] {process_utils.py:190} INFO - 
[2025-05-03T00:18:47.258+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2025-05-03T00:18:47.258+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 189, in http_request
[2025-05-03T00:18:47.259+0000] {process_utils.py:190} INFO -     return _get_http_response_with_retries(
[2025-05-03T00:18:47.259+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/utils/request_utils.py", line 237, in _get_http_response_with_retries
[2025-05-03T00:18:47.259+0000] {process_utils.py:190} INFO -     return session.request(method, url, allow_redirects=allow_redirects, **kwargs)
[2025-05-03T00:18:47.259+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
[2025-05-03T00:18:47.260+0000] {process_utils.py:190} INFO -     resp = self.send(prep, **send_kwargs)
[2025-05-03T00:18:47.260+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
[2025-05-03T00:18:47.260+0000] {process_utils.py:190} INFO -     r = adapter.send(request, **kwargs)
[2025-05-03T00:18:47.260+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
[2025-05-03T00:18:47.261+0000] {process_utils.py:190} INFO -     raise ConnectionError(e, request=request)
[2025-05-03T00:18:47.261+0000] {process_utils.py:190} INFO - requests.exceptions.ConnectionError: HTTPConnectionPool(host='mlflow', port=5000): Max retries exceeded with url: /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stroke+Prediction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81f079e670>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2025-05-03T00:18:47.261+0000] {process_utils.py:190} INFO - 
[2025-05-03T00:18:47.262+0000] {process_utils.py:190} INFO - During handling of the above exception, another exception occurred:
[2025-05-03T00:18:47.262+0000] {process_utils.py:190} INFO - 
[2025-05-03T00:18:47.262+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2025-05-03T00:18:47.262+0000] {process_utils.py:190} INFO -   File "/tmp/venv-call0icbvqxy/script.py", line 123, in <module>
[2025-05-03T00:18:47.263+0000] {process_utils.py:190} INFO -     res = get_data(*arg_dict["args"], **arg_dict["kwargs"])
[2025-05-03T00:18:47.263+0000] {process_utils.py:190} INFO -   File "/tmp/venv-call0icbvqxy/script.py", line 80, in get_data
[2025-05-03T00:18:47.263+0000] {process_utils.py:190} INFO -     experiment = mlflow.set_experiment("Stroke Prediction")
[2025-05-03T00:18:47.263+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 145, in set_experiment
[2025-05-03T00:18:47.264+0000] {process_utils.py:190} INFO -     experiment = client.get_experiment_by_name(experiment_name)
[2025-05-03T00:18:47.264+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/tracking/client.py", line 1256, in get_experiment_by_name
[2025-05-03T00:18:47.264+0000] {process_utils.py:190} INFO -     return self._tracking_client.get_experiment_by_name(name)
[2025-05-03T00:18:47.264+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 501, in get_experiment_by_name
[2025-05-03T00:18:47.265+0000] {process_utils.py:190} INFO -     return self.store.get_experiment_by_name(name)
[2025-05-03T00:18:47.265+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 519, in get_experiment_by_name
[2025-05-03T00:18:47.265+0000] {process_utils.py:190} INFO -     response_proto = self._call_endpoint(GetExperimentByName, req_body)
[2025-05-03T00:18:47.265+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 82, in _call_endpoint
[2025-05-03T00:18:47.266+0000] {process_utils.py:190} INFO -     return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
[2025-05-03T00:18:47.266+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 365, in call_endpoint
[2025-05-03T00:18:47.266+0000] {process_utils.py:190} INFO -     response = http_request(**call_kwargs)
[2025-05-03T00:18:47.266+0000] {process_utils.py:190} INFO -   File "/home/***/.local/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 212, in http_request
[2025-05-03T00:18:47.267+0000] {process_utils.py:190} INFO -     raise MlflowException(f"API request to {url} failed with exception {e}")
[2025-05-03T00:18:47.267+0000] {process_utils.py:190} INFO - mlflow.exceptions.MlflowException: API request to http://mlflow:5000/api/2.0/mlflow/experiments/get-by-name failed with exception HTTPConnectionPool(host='mlflow', port=5000): Max retries exceeded with url: /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stroke+Prediction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81f079e670>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2025-05-03T00:18:47.536+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
API request to http://mlflow:5000/api/2.0/mlflow/experiments/get-by-name failed with exception HTTPConnectionPool(host='mlflow', port=5000): Max retries exceeded with url: /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stroke+Prediction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81f079e670>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2025-05-03T00:18:47.541+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=process_etl_stroke_data_v3, task_id=get_original_data, execution_date=20250502T000000, start_date=20250503T001738, end_date=20250503T001847
[2025-05-03T00:18:47.552+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 2 for task get_original_data (Process returned non-zero exit status 1.
API request to http://mlflow:5000/api/2.0/mlflow/experiments/get-by-name failed with exception HTTPConnectionPool(host='mlflow', port=5000): Max retries exceeded with url: /api/2.0/mlflow/experiments/get-by-name?experiment_name=Stroke+Prediction (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f81f079e670>: Failed to establish a new connection: [Errno 111] Connection refused')); 752)
[2025-05-03T00:18:47.559+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-03T00:18:47.575+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T00:53:07.764+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T00:53:07.773+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T00:53:07.773+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-03T00:53:07.784+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): get_original_data> on 2025-05-02 00:00:00+00:00
[2025-05-03T00:53:07.791+0000] {standard_task_runner.py:60} INFO - Started process 310 to run task
[2025-05-03T00:53:07.800+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'get_original_data', 'scheduled__2025-05-02T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmpp0iyrads']
[2025-05-03T00:53:07.804+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask get_original_data
[2025-05-03T00:53:07.890+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-02T00:00:00+00:00 [running]> on host c624b4368fe1
[2025-05-03T00:53:08.013+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='get_original_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-02T00:00:00+00:00'
[2025-05-03T00:53:08.018+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv7gehvm66 --system-site-packages --python=python
[2025-05-03T00:53:08.024+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T00:53:08.881+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 418ms
[2025-05-03T00:53:08.881+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv7gehvm66, clear=False, no_vcs_ignore=False, global=True)
[2025-05-03T00:53:08.882+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmpbujv8be2)
[2025-05-03T00:53:08.883+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-03T00:53:08.883+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-03T00:53:08.906+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv7gehvm66/bin/pip install -r /tmp/venv7gehvm66/requirements.txt
[2025-05-03T00:53:08.911+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T00:53:09.542+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-03T00:53:09.918+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venv7gehvm66/requirements.txt (line 1))
[2025-05-03T00:53:10.000+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-03T00:53:10.002+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv7gehvm66/requirements.txt (line 2)) (2.17.2)
[2025-05-03T00:53:10.003+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv7gehvm66/requirements.txt (line 3)) (2.0.3)
[2025-05-03T00:53:10.037+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv7gehvm66/requirements.txt (line 1)) (1.37.38)
[2025-05-03T00:53:10.038+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv7gehvm66/requirements.txt (line 1)) (1.37.38)
[2025-05-03T00:53:10.039+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv7gehvm66/requirements.txt (line 1)) (1.24.4)
[2025-05-03T00:53:10.039+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv7gehvm66/requirements.txt (line 1)) (23.2)
[2025-05-03T00:53:10.040+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv7gehvm66/requirements.txt (line 1)) (14.0.2)
[2025-05-03T00:53:10.040+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv7gehvm66/requirements.txt (line 1)) (4.9.0)
[2025-05-03T00:53:10.084+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (2.17.2)
[2025-05-03T00:53:10.085+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (2.2.5)
[2025-05-03T00:53:10.086+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (1.13.1)
[2025-05-03T00:53:10.086+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (7.0.0)
[2025-05-03T00:53:10.087+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (3.4.3)
[2025-05-03T00:53:10.087+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (3.5.2)
[2025-05-03T00:53:10.088+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (3.7.5)
[2025-05-03T00:53:10.088+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (1.3.2)
[2025-05-03T00:53:10.089+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (1.10.1)
[2025-05-03T00:53:10.090+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (1.4.51)
[2025-05-03T00:53:10.092+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (3.1.3)
[2025-05-03T00:53:10.093+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (21.2.0)
[2025-05-03T00:53:10.132+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (5.3.2)
[2025-05-03T00:53:10.133+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (8.1.7)
[2025-05-03T00:53:10.134+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (3.1.1)
[2025-05-03T00:53:10.134+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (0.51.0)
[2025-05-03T00:53:10.135+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (3.1.44)
[2025-05-03T00:53:10.135+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (6.11.0)
[2025-05-03T00:53:10.135+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (1.22.0)
[2025-05-03T00:53:10.140+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (1.22.0)
[2025-05-03T00:53:10.142+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (4.25.2)
[2025-05-03T00:53:10.143+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (6.0.1)
[2025-05-03T00:53:10.144+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (2.31.0)
[2025-05-03T00:53:10.145+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (0.4.4)
[2025-05-03T00:53:10.244+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venv7gehvm66/requirements.txt (line 3)) (2.8.2)
[2025-05-03T00:53:10.245+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venv7gehvm66/requirements.txt (line 3)) (2023.3.post1)
[2025-05-03T00:53:10.246+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venv7gehvm66/requirements.txt (line 3)) (2023.4)
[2025-05-03T00:53:10.270+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (1.3.0)
[2025-05-03T00:53:10.271+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (5.13.0)
[2025-05-03T00:53:10.277+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venv7gehvm66/requirements.txt (line 1)) (0.10.0)
[2025-05-03T00:53:10.278+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venv7gehvm66/requirements.txt (line 1)) (0.11.5)
[2025-05-03T00:53:10.284+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venv7gehvm66/requirements.txt (line 1)) (1.26.18)
[2025-05-03T00:53:10.296+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (2.2.3)
[2025-05-03T00:53:10.296+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (2.1.2)
[2025-05-03T00:53:10.315+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (3.2.6)
[2025-05-03T00:53:10.315+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (3.2.0)
[2025-05-03T00:53:10.325+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (2.1.3)
[2025-05-03T00:53:10.345+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (1.1.1)
[2025-05-03T00:53:10.346+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (0.12.1)
[2025-05-03T00:53:10.347+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (4.57.0)
[2025-05-03T00:53:10.347+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (1.4.7)
[2025-05-03T00:53:10.348+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (10.4.0)
[2025-05-03T00:53:10.349+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (3.1.1)
[2025-05-03T00:53:10.362+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas->-r /tmp/venv7gehvm66/requirements.txt (line 3)) (1.16.0)
[2025-05-03T00:53:10.394+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (1.4.2)
[2025-05-03T00:53:10.395+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (3.5.0)
[2025-05-03T00:53:10.472+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (3.0.3)
[2025-05-03T00:53:10.533+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (2.26.2)
[2025-05-03T00:53:10.580+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (4.0.12)
[2025-05-03T00:53:10.615+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (3.17.0)
[2025-05-03T00:53:10.653+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (1.2.14)
[2025-05-03T00:53:10.659+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (0.43b0)
[2025-05-03T00:53:10.702+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (3.3.2)
[2025-05-03T00:53:10.703+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (3.6)
[2025-05-03T00:53:10.704+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (2023.11.17)
[2025-05-03T00:53:10.771+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (1.16.0)
[2025-05-03T00:53:10.778+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (5.0.2)
[2025-05-03T00:53:10.790+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (0.3.0)
[2025-05-03T00:53:10.790+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (4.9)
[2025-05-03T00:53:10.817+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv7gehvm66/requirements.txt (line 2)) (0.5.1)
[2025-05-03T00:53:10.849+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-03T00:53:10.882+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 13.3 MB/s eta 0:00:00
[2025-05-03T00:53:13.166+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-03T00:53:13.396+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-03T00:53:13.538+0000] {process_utils.py:190} INFO - 
[2025-05-03T00:53:13.539+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-03T00:53:13.540+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-03T00:53:13.785+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv7gehvm66/bin/python /tmp/venv-callycvb9g6c/script.py /tmp/venv-callycvb9g6c/script.in /tmp/venv-callycvb9g6c/script.out /tmp/venv-callycvb9g6c/string_args.txt /tmp/venv-callycvb9g6c/termination.log
[2025-05-03T00:53:13.794+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T00:53:14.797+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-03T00:53:18.102+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:18.101+0000[0m] {[34mscript.py:[0m49} INFO[0m - Starting to read the dataset from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-03T00:53:18.136+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:18.136+0000[0m] {[34mscript.py:[0m59} INFO[0m - Dataset read successfully from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-03T00:53:18.137+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:18.136+0000[0m] {[34mscript.py:[0m60} INFO[0m - Dataset shape: (5110, 12)[0m
[2025-05-03T00:53:18.139+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:18.139+0000[0m] {[34mscript.py:[0m76} INFO[0m - Dataset columns: ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke'][0m
[2025-05-03T00:53:18.737+0000] {process_utils.py:190} INFO - 2025/05/03 00:53:18 INFO mlflow.tracking.fluent: Experiment with name 'Stroke Prediction' does not exist. Creating a new experiment.
[2025-05-03T00:53:20.379+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:20.378+0000[0m] {[34mscript.py:[0m106} INFO[0m - Logged dataset information to MLflow in run: get_data_20250503_005319[0m
[2025-05-03T00:53:20.444+0000] {process_utils.py:190} INFO - 2025/05/03 00:53:20 INFO mlflow.tracking._tracking_service.client: 🏃 View run get_data_20250503_005319 at: http://mlflow:5000/#/experiments/1/runs/d57cfae576d54082b84ab79e22f7cbe4.
[2025-05-03T00:53:20.445+0000] {process_utils.py:190} INFO - 2025/05/03 00:53:20 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-03T00:53:20.480+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:20.480+0000[0m] {[34mscript.py:[0m112} INFO[0m - Starting to save the dataset to S3/Minio at s3://data/raw/stroke_data.csv[0m
[2025-05-03T00:53:20.491+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:20.491+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T00:53:20.722+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:20.721+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T00:53:20.775+0000] {process_utils.py:190} INFO - [[34m2025-05-03T00:53:20.774+0000[0m] {[34mscript.py:[0m117} INFO[0m - Dataset saved successfully to s3://data/raw/stroke_data.csv[0m
[2025-05-03T00:53:21.142+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-03T00:53:21.153+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=get_original_data, execution_date=20250502T000000, start_date=20250503T005307, end_date=20250503T005321
[2025-05-03T00:53:21.179+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-03T00:53:21.203+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-03T04:58:04.669+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T04:58:04.678+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T04:58:04.679+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-03T04:58:04.691+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): get_original_data> on 2025-05-02 00:00:00+00:00
[2025-05-03T04:58:04.697+0000] {standard_task_runner.py:60} INFO - Started process 733 to run task
[2025-05-03T04:58:04.700+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'get_original_data', 'scheduled__2025-05-02T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmpc0nlc6pl']
[2025-05-03T04:58:04.704+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask get_original_data
[2025-05-03T04:58:04.763+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-02T00:00:00+00:00 [running]> on host 75c2609a33dd
[2025-05-03T04:58:04.826+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='get_original_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-02T00:00:00+00:00'
[2025-05-03T04:58:04.830+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvms_l2x6d --system-site-packages --python=python
[2025-05-03T04:58:04.838+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T04:58:05.702+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 491ms
[2025-05-03T04:58:05.703+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvms_l2x6d, clear=False, no_vcs_ignore=False, global=True)
[2025-05-03T04:58:05.704+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmpo4j29yg7)
[2025-05-03T04:58:05.705+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-03T04:58:05.705+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-03T04:58:05.727+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvms_l2x6d/bin/pip install -r /tmp/venvms_l2x6d/requirements.txt
[2025-05-03T04:58:05.735+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T04:58:06.560+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-03T04:58:07.053+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venvms_l2x6d/requirements.txt (line 1))
[2025-05-03T04:58:07.105+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-03T04:58:07.109+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvms_l2x6d/requirements.txt (line 2)) (2.17.2)
[2025-05-03T04:58:07.109+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvms_l2x6d/requirements.txt (line 3)) (2.0.3)
[2025-05-03T04:58:07.143+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvms_l2x6d/requirements.txt (line 1)) (1.37.38)
[2025-05-03T04:58:07.144+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvms_l2x6d/requirements.txt (line 1)) (1.37.38)
[2025-05-03T04:58:07.145+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvms_l2x6d/requirements.txt (line 1)) (1.24.4)
[2025-05-03T04:58:07.146+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvms_l2x6d/requirements.txt (line 1)) (23.2)
[2025-05-03T04:58:07.146+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvms_l2x6d/requirements.txt (line 1)) (14.0.2)
[2025-05-03T04:58:07.147+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvms_l2x6d/requirements.txt (line 1)) (4.9.0)
[2025-05-03T04:58:07.183+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (2.17.2)
[2025-05-03T04:58:07.184+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (2.2.5)
[2025-05-03T04:58:07.184+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (1.13.1)
[2025-05-03T04:58:07.185+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (7.0.0)
[2025-05-03T04:58:07.185+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (3.4.3)
[2025-05-03T04:58:07.186+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (3.5.2)
[2025-05-03T04:58:07.186+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (3.7.5)
[2025-05-03T04:58:07.187+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (1.3.2)
[2025-05-03T04:58:07.187+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (1.10.1)
[2025-05-03T04:58:07.188+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (1.4.51)
[2025-05-03T04:58:07.189+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (3.1.3)
[2025-05-03T04:58:07.190+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (21.2.0)
[2025-05-03T04:58:07.227+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (5.3.2)
[2025-05-03T04:58:07.228+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (8.1.7)
[2025-05-03T04:58:07.228+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (3.1.1)
[2025-05-03T04:58:07.229+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (0.51.0)
[2025-05-03T04:58:07.230+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (3.1.44)
[2025-05-03T04:58:07.231+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (6.11.0)
[2025-05-03T04:58:07.231+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (1.22.0)
[2025-05-03T04:58:07.231+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (1.22.0)
[2025-05-03T04:58:07.232+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (4.25.2)
[2025-05-03T04:58:07.232+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (6.0.1)
[2025-05-03T04:58:07.233+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (2.31.0)
[2025-05-03T04:58:07.234+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (0.4.4)
[2025-05-03T04:58:07.309+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvms_l2x6d/requirements.txt (line 3)) (2.8.2)
[2025-05-03T04:58:07.310+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvms_l2x6d/requirements.txt (line 3)) (2023.3.post1)
[2025-05-03T04:58:07.311+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvms_l2x6d/requirements.txt (line 3)) (2023.4)
[2025-05-03T04:58:07.332+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (1.3.0)
[2025-05-03T04:58:07.333+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (5.13.0)
[2025-05-03T04:58:07.338+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvms_l2x6d/requirements.txt (line 1)) (0.10.0)
[2025-05-03T04:58:07.339+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvms_l2x6d/requirements.txt (line 1)) (0.11.5)
[2025-05-03T04:58:07.346+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvms_l2x6d/requirements.txt (line 1)) (1.26.18)
[2025-05-03T04:58:07.359+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (2.2.3)
[2025-05-03T04:58:07.360+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (2.1.2)
[2025-05-03T04:58:07.378+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (3.2.6)
[2025-05-03T04:58:07.379+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (3.2.0)
[2025-05-03T04:58:07.389+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (2.1.3)
[2025-05-03T04:58:07.417+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (1.1.1)
[2025-05-03T04:58:07.418+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (0.12.1)
[2025-05-03T04:58:07.418+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (4.57.0)
[2025-05-03T04:58:07.419+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (1.4.7)
[2025-05-03T04:58:07.420+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (10.4.0)
[2025-05-03T04:58:07.421+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (3.1.1)
[2025-05-03T04:58:07.432+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas->-r /tmp/venvms_l2x6d/requirements.txt (line 3)) (1.16.0)
[2025-05-03T04:58:07.464+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (1.4.2)
[2025-05-03T04:58:07.465+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (3.5.0)
[2025-05-03T04:58:07.550+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (3.0.3)
[2025-05-03T04:58:07.611+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (2.26.2)
[2025-05-03T04:58:07.660+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (4.0.12)
[2025-05-03T04:58:07.697+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (3.17.0)
[2025-05-03T04:58:07.745+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (1.2.14)
[2025-05-03T04:58:07.752+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (0.43b0)
[2025-05-03T04:58:07.802+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (3.3.2)
[2025-05-03T04:58:07.804+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (3.6)
[2025-05-03T04:58:07.804+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (2023.11.17)
[2025-05-03T04:58:07.891+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (1.16.0)
[2025-05-03T04:58:07.898+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (5.0.2)
[2025-05-03T04:58:07.914+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (0.3.0)
[2025-05-03T04:58:07.915+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (4.9)
[2025-05-03T04:58:07.950+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvms_l2x6d/requirements.txt (line 2)) (0.5.1)
[2025-05-03T04:58:07.991+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-03T04:58:08.034+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 9.5 MB/s eta 0:00:00
[2025-05-03T04:58:10.506+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-03T04:58:10.785+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-03T04:58:10.892+0000] {process_utils.py:190} INFO - 
[2025-05-03T04:58:10.893+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-03T04:58:10.893+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-03T04:58:11.049+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvms_l2x6d/bin/python /tmp/venv-callhk1v5xrc/script.py /tmp/venv-callhk1v5xrc/script.in /tmp/venv-callhk1v5xrc/script.out /tmp/venv-callhk1v5xrc/string_args.txt /tmp/venv-callhk1v5xrc/termination.log
[2025-05-03T04:58:11.065+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T04:58:11.684+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-03T04:58:15.081+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:15.080+0000[0m] {[34mscript.py:[0m49} INFO[0m - Starting to read the dataset from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-03T04:58:15.115+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:15.114+0000[0m] {[34mscript.py:[0m59} INFO[0m - Dataset read successfully from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-03T04:58:15.118+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:15.115+0000[0m] {[34mscript.py:[0m60} INFO[0m - Dataset shape: (5110, 12)[0m
[2025-05-03T04:58:15.125+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:15.118+0000[0m] {[34mscript.py:[0m76} INFO[0m - Dataset columns: ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke'][0m
[2025-05-03T04:58:16.505+0000] {process_utils.py:190} INFO - 2025/05/03 04:58:16 INFO mlflow.tracking.fluent: Experiment with name 'Stroke Prediction' does not exist. Creating a new experiment.
[2025-05-03T04:58:16.875+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:16.875+0000[0m] {[34mscript.py:[0m106} INFO[0m - Logged dataset information to MLflow in run: get_data_20250503_045816[0m
[2025-05-03T04:58:16.937+0000] {process_utils.py:190} INFO - 2025/05/03 04:58:16 INFO mlflow.tracking._tracking_service.client: 🏃 View run get_data_20250503_045816 at: http://mlflow:5000/#/experiments/1/runs/a0b18ec6e9d4419b9324942865729fe3.
[2025-05-03T04:58:16.940+0000] {process_utils.py:190} INFO - 2025/05/03 04:58:16 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-03T04:58:16.971+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:16.971+0000[0m] {[34mscript.py:[0m112} INFO[0m - Starting to save the dataset to S3/Minio at s3://data/raw/stroke_data.csv[0m
[2025-05-03T04:58:16.988+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:16.987+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T04:58:17.398+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:17.398+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T04:58:17.494+0000] {process_utils.py:190} INFO - [[34m2025-05-03T04:58:17.493+0000[0m] {[34mscript.py:[0m117} INFO[0m - Dataset saved successfully to s3://data/raw/stroke_data.csv[0m
[2025-05-03T04:58:17.919+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-03T04:58:17.933+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=get_original_data, execution_date=20250502T000000, start_date=20250503T045804, end_date=20250503T045817
[2025-05-03T04:58:17.977+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-03T04:58:18.002+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-03T13:43:55.387+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T13:43:55.408+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T13:43:55.408+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-03T13:43:55.432+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): get_original_data> on 2025-05-02 00:00:00+00:00
[2025-05-03T13:43:55.451+0000] {standard_task_runner.py:60} INFO - Started process 605 to run task
[2025-05-03T13:43:55.467+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'get_original_data', 'scheduled__2025-05-02T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmpuajdyy35']
[2025-05-03T13:43:55.479+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask get_original_data
[2025-05-03T13:43:55.748+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-02T00:00:00+00:00 [running]> on host 8fb4c1e7dfa6
[2025-05-03T13:43:55.922+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='get_original_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-02T00:00:00+00:00'
[2025-05-03T13:43:55.930+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv6t9m72yb --system-site-packages --python=python
[2025-05-03T13:43:55.937+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T13:43:57.406+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 588ms
[2025-05-03T13:43:57.406+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv6t9m72yb, clear=False, no_vcs_ignore=False, global=True)
[2025-05-03T13:43:57.407+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmpkb8qq3ln)
[2025-05-03T13:43:57.408+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-03T13:43:57.408+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-03T13:43:57.436+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv6t9m72yb/bin/pip install -r /tmp/venv6t9m72yb/requirements.txt
[2025-05-03T13:43:57.458+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T13:43:58.139+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-03T13:43:58.643+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venv6t9m72yb/requirements.txt (line 1))
[2025-05-03T13:43:58.706+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-03T13:43:58.709+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv6t9m72yb/requirements.txt (line 2)) (2.17.2)
[2025-05-03T13:43:58.710+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv6t9m72yb/requirements.txt (line 3)) (2.0.3)
[2025-05-03T13:43:58.743+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv6t9m72yb/requirements.txt (line 1)) (1.37.38)
[2025-05-03T13:43:58.744+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv6t9m72yb/requirements.txt (line 1)) (1.37.38)
[2025-05-03T13:43:58.745+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv6t9m72yb/requirements.txt (line 1)) (1.24.4)
[2025-05-03T13:43:58.745+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv6t9m72yb/requirements.txt (line 1)) (23.2)
[2025-05-03T13:43:58.746+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv6t9m72yb/requirements.txt (line 1)) (14.0.2)
[2025-05-03T13:43:58.747+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venv6t9m72yb/requirements.txt (line 1)) (4.9.0)
[2025-05-03T13:43:58.786+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (2.17.2)
[2025-05-03T13:43:58.787+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (2.2.5)
[2025-05-03T13:43:58.787+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (1.13.1)
[2025-05-03T13:43:58.788+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (7.0.0)
[2025-05-03T13:43:58.788+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (3.4.3)
[2025-05-03T13:43:58.789+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (3.5.2)
[2025-05-03T13:43:58.789+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (3.7.5)
[2025-05-03T13:43:58.790+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (1.3.2)
[2025-05-03T13:43:58.790+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (1.10.1)
[2025-05-03T13:43:58.792+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (1.4.51)
[2025-05-03T13:43:58.793+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (3.1.3)
[2025-05-03T13:43:58.794+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (21.2.0)
[2025-05-03T13:43:58.833+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (5.3.2)
[2025-05-03T13:43:58.834+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (8.1.7)
[2025-05-03T13:43:58.835+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (3.1.1)
[2025-05-03T13:43:58.835+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (0.51.0)
[2025-05-03T13:43:58.836+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (3.1.44)
[2025-05-03T13:43:58.836+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (6.11.0)
[2025-05-03T13:43:58.837+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (1.22.0)
[2025-05-03T13:43:58.837+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (1.22.0)
[2025-05-03T13:43:58.838+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (4.25.2)
[2025-05-03T13:43:58.839+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (6.0.1)
[2025-05-03T13:43:58.840+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (2.31.0)
[2025-05-03T13:43:58.841+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (0.4.4)
[2025-05-03T13:43:58.907+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venv6t9m72yb/requirements.txt (line 3)) (2.8.2)
[2025-05-03T13:43:58.908+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venv6t9m72yb/requirements.txt (line 3)) (2023.3.post1)
[2025-05-03T13:43:58.909+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venv6t9m72yb/requirements.txt (line 3)) (2023.4)
[2025-05-03T13:43:58.928+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (1.3.0)
[2025-05-03T13:43:58.929+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (5.13.0)
[2025-05-03T13:43:58.934+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venv6t9m72yb/requirements.txt (line 1)) (0.10.0)
[2025-05-03T13:43:58.935+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venv6t9m72yb/requirements.txt (line 1)) (0.11.5)
[2025-05-03T13:43:58.941+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venv6t9m72yb/requirements.txt (line 1)) (1.26.18)
[2025-05-03T13:43:58.953+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (2.2.3)
[2025-05-03T13:43:58.954+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (2.1.2)
[2025-05-03T13:43:58.970+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (3.2.6)
[2025-05-03T13:43:58.971+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (3.2.0)
[2025-05-03T13:43:58.980+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (2.1.3)
[2025-05-03T13:43:58.998+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (1.1.1)
[2025-05-03T13:43:58.999+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (0.12.1)
[2025-05-03T13:43:59.000+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (4.57.0)
[2025-05-03T13:43:59.000+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (1.4.7)
[2025-05-03T13:43:59.001+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (10.4.0)
[2025-05-03T13:43:59.001+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (3.1.1)
[2025-05-03T13:43:59.012+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas->-r /tmp/venv6t9m72yb/requirements.txt (line 3)) (1.16.0)
[2025-05-03T13:43:59.047+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (1.4.2)
[2025-05-03T13:43:59.048+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (3.5.0)
[2025-05-03T13:43:59.125+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (3.0.3)
[2025-05-03T13:43:59.184+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (2.26.2)
[2025-05-03T13:43:59.235+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (4.0.12)
[2025-05-03T13:43:59.270+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (3.17.0)
[2025-05-03T13:43:59.309+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (1.2.14)
[2025-05-03T13:43:59.316+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (0.43b0)
[2025-05-03T13:43:59.362+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (3.3.2)
[2025-05-03T13:43:59.363+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (3.6)
[2025-05-03T13:43:59.364+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (2023.11.17)
[2025-05-03T13:43:59.440+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (1.16.0)
[2025-05-03T13:43:59.448+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (5.0.2)
[2025-05-03T13:43:59.463+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (0.3.0)
[2025-05-03T13:43:59.464+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (4.9)
[2025-05-03T13:43:59.496+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venv6t9m72yb/requirements.txt (line 2)) (0.5.1)
[2025-05-03T13:43:59.533+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-03T13:43:59.565+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 13.1 MB/s eta 0:00:00
[2025-05-03T13:44:01.902+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-03T13:44:02.180+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-03T13:44:02.446+0000] {process_utils.py:190} INFO - 
[2025-05-03T13:44:02.447+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-03T13:44:02.449+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-03T13:44:02.630+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv6t9m72yb/bin/python /tmp/venv-call1_c8ad2v/script.py /tmp/venv-call1_c8ad2v/script.in /tmp/venv-call1_c8ad2v/script.out /tmp/venv-call1_c8ad2v/string_args.txt /tmp/venv-call1_c8ad2v/termination.log
[2025-05-03T13:44:02.648+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T13:44:03.442+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-03T13:44:07.725+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:07.724+0000[0m] {[34mscript.py:[0m49} INFO[0m - Starting to read the dataset from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-03T13:44:07.749+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:07.749+0000[0m] {[34mscript.py:[0m59} INFO[0m - Dataset read successfully from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-03T13:44:07.750+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:07.749+0000[0m] {[34mscript.py:[0m60} INFO[0m - Dataset shape: (5110, 12)[0m
[2025-05-03T13:44:07.752+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:07.752+0000[0m] {[34mscript.py:[0m76} INFO[0m - Dataset columns: ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke'][0m
[2025-05-03T13:44:10.806+0000] {process_utils.py:190} INFO - 2025/05/03 13:44:10 INFO mlflow.tracking.fluent: Experiment with name 'Stroke Prediction' does not exist. Creating a new experiment.
[2025-05-03T13:44:11.142+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:11.142+0000[0m] {[34mscript.py:[0m106} INFO[0m - Logged dataset information to MLflow in run: get_data_20250503_134410[0m
[2025-05-03T13:44:11.186+0000] {process_utils.py:190} INFO - 2025/05/03 13:44:11 INFO mlflow.tracking._tracking_service.client: 🏃 View run get_data_20250503_134410 at: http://mlflow:5000/#/experiments/1/runs/b0a84187f4b24d599fbc8873ccb000fe.
[2025-05-03T13:44:11.187+0000] {process_utils.py:190} INFO - 2025/05/03 13:44:11 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-03T13:44:13.992+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:13.992+0000[0m] {[34mscript.py:[0m112} INFO[0m - Starting to save the dataset to S3/Minio at s3://data/raw/stroke_data.csv[0m
[2025-05-03T13:44:14.002+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:14.002+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T13:44:14.915+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:14.914+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T13:44:15.001+0000] {process_utils.py:190} INFO - [[34m2025-05-03T13:44:15.000+0000[0m] {[34mscript.py:[0m117} INFO[0m - Dataset saved successfully to s3://data/raw/stroke_data.csv[0m
[2025-05-03T13:44:15.342+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-03T13:44:15.352+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=get_original_data, execution_date=20250502T000000, start_date=20250503T134355, end_date=20250503T134415
[2025-05-03T13:44:15.389+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-03T13:44:15.412+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-03T18:02:04.623+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T18:02:04.631+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-02T00:00:00+00:00 [queued]>
[2025-05-03T18:02:04.631+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-03T18:02:04.643+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): get_original_data> on 2025-05-02 00:00:00+00:00
[2025-05-03T18:02:04.650+0000] {standard_task_runner.py:60} INFO - Started process 652 to run task
[2025-05-03T18:02:04.652+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'process_etl_stroke_data_v3', 'get_original_data', 'scheduled__2025-05-02T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/etl_processing.py', '--cfg-path', '/tmp/tmpmpupjpe8']
[2025-05-03T18:02:04.654+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask get_original_data
[2025-05-03T18:02:04.702+0000] {task_command.py:423} INFO - Running <TaskInstance: process_etl_stroke_data_v3.get_original_data scheduled__2025-05-02T00:00:00+00:00 [running]> on host 2042e9a26c53
[2025-05-03T18:02:04.765+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Brain Stroke Project' AIRFLOW_CTX_DAG_ID='process_etl_stroke_data_v3' AIRFLOW_CTX_TASK_ID='get_original_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-02T00:00:00+00:00'
[2025-05-03T18:02:04.767+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvjgrtsf3m --system-site-packages --python=python
[2025-05-03T18:02:04.777+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T18:02:05.547+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 417ms
[2025-05-03T18:02:05.548+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvjgrtsf3m, clear=False, no_vcs_ignore=False, global=True)
[2025-05-03T18:02:05.548+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/tmp2l6obp84)
[2025-05-03T18:02:05.549+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2025-05-03T18:02:05.549+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-05-03T18:02:05.569+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvjgrtsf3m/bin/pip install -r /tmp/venvjgrtsf3m/requirements.txt
[2025-05-03T18:02:05.583+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T18:02:06.210+0000] {process_utils.py:190} INFO - WARNING: The directory '/home/***/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
[2025-05-03T18:02:06.653+0000] {process_utils.py:190} INFO - Collecting awswrangler==3.9.1 (from -r /tmp/venvjgrtsf3m/requirements.txt (line 1))
[2025-05-03T18:02:06.739+0000] {process_utils.py:190} INFO -   Downloading awswrangler-3.9.1-py3-none-any.whl.metadata (17 kB)
[2025-05-03T18:02:06.742+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow>=2.8.0 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (2.17.2)
[2025-05-03T18:02:06.743+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvjgrtsf3m/requirements.txt (line 3)) (2.0.3)
[2025-05-03T18:02:06.773+0000] {process_utils.py:190} INFO - Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvjgrtsf3m/requirements.txt (line 1)) (1.37.38)
[2025-05-03T18:02:06.774+0000] {process_utils.py:190} INFO - Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvjgrtsf3m/requirements.txt (line 1)) (1.37.38)
[2025-05-03T18:02:06.775+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2.0,>=1.18 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvjgrtsf3m/requirements.txt (line 1)) (1.24.4)
[2025-05-03T18:02:06.776+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<25.0,>=21.1 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvjgrtsf3m/requirements.txt (line 1)) (23.2)
[2025-05-03T18:02:06.776+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow>=8.0.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvjgrtsf3m/requirements.txt (line 1)) (14.0.2)
[2025-05-03T18:02:06.777+0000] {process_utils.py:190} INFO - Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /home/***/.local/lib/python3.8/site-packages (from awswrangler==3.9.1->-r /tmp/venvjgrtsf3m/requirements.txt (line 1)) (4.9.0)
[2025-05-03T18:02:06.810+0000] {process_utils.py:190} INFO - Requirement already satisfied: mlflow-skinny==2.17.2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (2.17.2)
[2025-05-03T18:02:06.810+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (2.2.5)
[2025-05-03T18:02:06.811+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (1.13.1)
[2025-05-03T18:02:06.811+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (7.0.0)
[2025-05-03T18:02:06.812+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphene<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (3.4.3)
[2025-05-03T18:02:06.813+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (3.5.2)
[2025-05-03T18:02:06.813+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (3.7.5)
[2025-05-03T18:02:06.814+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (1.3.2)
[2025-05-03T18:02:06.814+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (1.10.1)
[2025-05-03T18:02:06.815+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (1.4.51)
[2025-05-03T18:02:06.816+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (3.1.3)
[2025-05-03T18:02:06.817+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (21.2.0)
[2025-05-03T18:02:06.848+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6,>=5.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (5.3.2)
[2025-05-03T18:02:06.849+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (8.1.7)
[2025-05-03T18:02:06.849+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (3.1.1)
[2025-05-03T18:02:06.850+0000] {process_utils.py:190} INFO - Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (0.51.0)
[2025-05-03T18:02:06.850+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=3.1.9 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (3.1.44)
[2025-05-03T18:02:06.850+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<9,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (6.11.0)
[2025-05-03T18:02:06.851+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (1.22.0)
[2025-05-03T18:02:06.852+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (1.22.0)
[2025-05-03T18:02:06.852+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<6,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (4.25.2)
[2025-05-03T18:02:06.854+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (6.0.1)
[2025-05-03T18:02:06.854+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (2.31.0)
[2025-05-03T18:02:06.855+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (0.4.4)
[2025-05-03T18:02:06.912+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvjgrtsf3m/requirements.txt (line 3)) (2.8.2)
[2025-05-03T18:02:06.913+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvjgrtsf3m/requirements.txt (line 3)) (2023.3.post1)
[2025-05-03T18:02:06.914+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas->-r /tmp/venvjgrtsf3m/requirements.txt (line 3)) (2023.4)
[2025-05-03T18:02:06.936+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (1.3.0)
[2025-05-03T18:02:06.937+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (5.13.0)
[2025-05-03T18:02:06.947+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvjgrtsf3m/requirements.txt (line 1)) (0.10.0)
[2025-05-03T18:02:06.949+0000] {process_utils.py:190} INFO - Requirement already satisfied: s3transfer<0.12.0,>=0.11.0 in /home/***/.local/lib/python3.8/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler==3.9.1->-r /tmp/venvjgrtsf3m/requirements.txt (line 1)) (0.11.5)
[2025-05-03T18:02:06.957+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler==3.9.1->-r /tmp/venvjgrtsf3m/requirements.txt (line 1)) (1.26.18)
[2025-05-03T18:02:06.971+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (2.2.3)
[2025-05-03T18:02:06.971+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (2.1.2)
[2025-05-03T18:02:06.988+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-core<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (3.2.6)
[2025-05-03T18:02:06.989+0000] {process_utils.py:190} INFO - Requirement already satisfied: graphql-relay<3.3,>=3.1 in /home/***/.local/lib/python3.8/site-packages (from graphene<4->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (3.2.0)
[2025-05-03T18:02:06.998+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (2.1.3)
[2025-05-03T18:02:07.014+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (1.1.1)
[2025-05-03T18:02:07.015+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (0.12.1)
[2025-05-03T18:02:07.016+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (4.57.0)
[2025-05-03T18:02:07.016+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (1.4.7)
[2025-05-03T18:02:07.017+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (10.4.0)
[2025-05-03T18:02:07.018+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (3.1.1)
[2025-05-03T18:02:07.028+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas->-r /tmp/venvjgrtsf3m/requirements.txt (line 3)) (1.16.0)
[2025-05-03T18:02:07.055+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (1.4.2)
[2025-05-03T18:02:07.056+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn<2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (3.5.0)
[2025-05-03T18:02:07.117+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (3.0.3)
[2025-05-03T18:02:07.171+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth~=2.0 in /home/***/.local/lib/python3.8/site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (2.26.2)
[2025-05-03T18:02:07.214+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (4.0.12)
[2025-05-03T18:02:07.250+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (3.17.0)
[2025-05-03T18:02:07.286+0000] {process_utils.py:190} INFO - Requirement already satisfied: deprecated>=1.2.6 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (1.2.14)
[2025-05-03T18:02:07.293+0000] {process_utils.py:190} INFO - Requirement already satisfied: opentelemetry-semantic-conventions==0.43b0 in /home/***/.local/lib/python3.8/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (0.43b0)
[2025-05-03T18:02:07.338+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (3.3.2)
[2025-05-03T18:02:07.340+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (3.6)
[2025-05-03T18:02:07.341+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (2023.11.17)
[2025-05-03T18:02:07.416+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt<2,>=1.10 in /home/***/.local/lib/python3.8/site-packages (from deprecated>=1.2.6->opentelemetry-api<3,>=1.9.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (1.16.0)
[2025-05-03T18:02:07.421+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (5.0.2)
[2025-05-03T18:02:07.435+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (0.3.0)
[2025-05-03T18:02:07.435+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (4.9)
[2025-05-03T18:02:07.469+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==2.17.2->mlflow>=2.8.0->-r /tmp/venvjgrtsf3m/requirements.txt (line 2)) (0.5.1)
[2025-05-03T18:02:07.508+0000] {process_utils.py:190} INFO - Downloading awswrangler-3.9.1-py3-none-any.whl (381 kB)
[2025-05-03T18:02:07.534+0000] {process_utils.py:190} INFO -    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.7/381.7 kB 16.9 MB/s eta 0:00:00
[2025-05-03T18:02:09.577+0000] {process_utils.py:190} INFO - Installing collected packages: awswrangler
[2025-05-03T18:02:09.791+0000] {process_utils.py:190} INFO - Successfully installed awswrangler-3.9.1
[2025-05-03T18:02:09.878+0000] {process_utils.py:190} INFO - 
[2025-05-03T18:02:09.878+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 25.0.1
[2025-05-03T18:02:09.879+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-05-03T18:02:10.206+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvjgrtsf3m/bin/python /tmp/venv-callda1emd36/script.py /tmp/venv-callda1emd36/script.in /tmp/venv-callda1emd36/script.out /tmp/venv-callda1emd36/string_args.txt /tmp/venv-callda1emd36/termination.log
[2025-05-03T18:02:10.216+0000] {process_utils.py:186} INFO - Output:
[2025-05-03T18:02:10.849+0000] {process_utils.py:190} INFO - WARNING:root:/opt/***/logs/scheduler/latest already exists as a dir/file. Skip creating symlink.
[2025-05-03T18:02:14.195+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:14.193+0000[0m] {[34mscript.py:[0m49} INFO[0m - Starting to read the dataset from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-03T18:02:14.259+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:14.258+0000[0m] {[34mscript.py:[0m59} INFO[0m - Dataset read successfully from /opt/***/dataset/healthcare-dataset-stroke-data.csv[0m
[2025-05-03T18:02:14.260+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:14.259+0000[0m] {[34mscript.py:[0m60} INFO[0m - Dataset shape: (5110, 12)[0m
[2025-05-03T18:02:14.264+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:14.264+0000[0m] {[34mscript.py:[0m76} INFO[0m - Dataset columns: ['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married', 'work_type', 'residence_type', 'avg_glucose_level', 'bmi', 'smoking_status', 'stroke'][0m
[2025-05-03T18:02:14.324+0000] {process_utils.py:190} INFO - 2025/05/03 18:02:14 INFO mlflow.tracking.fluent: Experiment with name 'Stroke Prediction' does not exist. Creating a new experiment.
[2025-05-03T18:02:14.754+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:14.754+0000[0m] {[34mscript.py:[0m106} INFO[0m - Logged dataset information to MLflow in run: get_data_20250503_180214[0m
[2025-05-03T18:02:14.794+0000] {process_utils.py:190} INFO - 2025/05/03 18:02:14 INFO mlflow.tracking._tracking_service.client: 🏃 View run get_data_20250503_180214 at: http://mlflow:5000/#/experiments/1/runs/500f19256a45445090d403908b4200c1.
[2025-05-03T18:02:14.796+0000] {process_utils.py:190} INFO - 2025/05/03 18:02:14 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://mlflow:5000/#/experiments/1.
[2025-05-03T18:02:14.828+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:14.827+0000[0m] {[34mscript.py:[0m112} INFO[0m - Starting to save the dataset to S3/Minio at s3://data/raw/stroke_data.csv[0m
[2025-05-03T18:02:14.837+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:14.837+0000[0m] {[34mcredentials.py:[0m1213} INFO[0m - Found credentials in environment variables.[0m
[2025-05-03T18:02:14.997+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:14.997+0000[0m] {[34mconfigprovider.py:[0m998} INFO[0m - Found endpoint for s3 via: environment_service.[0m
[2025-05-03T18:02:15.044+0000] {process_utils.py:190} INFO - [[34m2025-05-03T18:02:15.044+0000[0m] {[34mscript.py:[0m117} INFO[0m - Dataset saved successfully to s3://data/raw/stroke_data.csv[0m
[2025-05-03T18:02:15.345+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-03T18:02:15.356+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=process_etl_stroke_data_v3, task_id=get_original_data, execution_date=20250502T000000, start_date=20250503T180204, end_date=20250503T180215
[2025-05-03T18:02:15.390+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-03T18:02:15.421+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
